In [21]:
import pandas as pd
import numpy as np

In [22]:
df = pd.read_csv('data.csv')
df

  delivery_id courier delivery_minutes     status
0        D101    Sato               35  Delivered
1        D102  tanaka               62  delivered
2        D103    SATO           eighty       Late
3        D104  Tanaka               -5  Delivered
4        D105     NaN               48       LATE
5        D105     NaN               48       LATE
6        D106  Suzuki              NaN   delivred

In [23]:
df["courier"] = df["courier"].str.capitalize()
df["courier"] = df["courier"].fillna("Unknown")
df

  delivery_id  courier delivery_minutes     status
0        D101     Sato               35  Delivered
1        D102   Tanaka               62  delivered
2        D103     Sato           eighty       Late
3        D104   Tanaka               -5  Delivered
4        D105  Unknown               48       LATE
5        D105  Unknown               48       LATE
6        D106   Suzuki              NaN   delivred

In [24]:
df["status"] = df["status"].str.replace("delivred", "Delivered")
df["status"] = df["status"].str.capitalize()
df

  delivery_id  courier delivery_minutes     status
0        D101     Sato               35  Delivered
1        D102   Tanaka               62  Delivered
2        D103     Sato           eighty       Late
3        D104   Tanaka               -5  Delivered
4        D105  Unknown               48       Late
5        D105  Unknown               48       Late
6        D106   Suzuki              NaN  Delivered

In [25]:
df["delivery_minutes"] = df["delivery_minutes"].replace({"-5":"5", "eighty":"80"})
df

  delivery_id  courier delivery_minutes     status
0        D101     Sato               35  Delivered
1        D102   Tanaka               62  Delivered
2        D103     Sato               80       Late
3        D104   Tanaka                5  Delivered
4        D105  Unknown               48       Late
5        D105  Unknown               48       Late
6        D106   Suzuki              NaN  Delivered

In [26]:
df["delivery_minutes"] = pd.to_numeric(df["delivery_minutes"])
df

  delivery_id  courier  delivery_minutes     status
0        D101     Sato              35.0  Delivered
1        D102   Tanaka              62.0  Delivered
2        D103     Sato              80.0       Late
3        D104   Tanaka               5.0  Delivered
4        D105  Unknown              48.0       Late
5        D105  Unknown              48.0       Late
6        D106   Suzuki               NaN  Delivered