In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_csv('data.csv')
df

  delivery_id courier delivery_minutes     status
0        D101    Sato               35  Delivered
1        D102  tanaka               62  delivered
2        D103    SATO           eighty       Late
3        D104  Tanaka               -5  Delivered
4        D105     NaN               48       LATE
5        D105     NaN               48       LATE
6        D106  Suzuki              NaN   delivred

In [3]:
df = df.drop_duplicates()

In [4]:
df

  delivery_id courier delivery_minutes     status
0        D101    Sato               35  Delivered
1        D102  tanaka               62  delivered
2        D103    SATO           eighty       Late
3        D104  Tanaka               -5  Delivered
4        D105     NaN               48       LATE
6        D106  Suzuki              NaN   delivred

In [5]:
df["courier"] = df["courier"].str.capitalize()
df["courier"] = df["courier"].fillna("Unknown")
df

C:\Users\sho_taso\AppData\Local\Temp\ipykernel_12784\4207158141.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["courier"] = df["courier"].str.capitalize()
C:\Users\sho_taso\AppData\Local\Temp\ipykernel_12784\4207158141.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["courier"] = df["courier"].fillna("Unknown")

  delivery_id  courier delivery_minutes     status
0        D101     Sato               35  Delivered
1        D102   Tanaka               62  delivered
2        D103     Sato           eighty       Late
3        D104   Tanaka               -5  Delivered
4        D105  Unknown               48       LATE
6        D106   Suzuki              NaN   delivred

In [6]:
df["status"] = df["status"].str.replace("delivred", "Delivered")
df["status"] = df["status"].str.capitalize()
df

C:\Users\sho_taso\AppData\Local\Temp\ipykernel_12784\2119349449.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["status"] = df["status"].str.replace("delivred", "Delivered")
C:\Users\sho_taso\AppData\Local\Temp\ipykernel_12784\2119349449.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["status"] = df["status"].str.capitalize()

  delivery_id  courier delivery_minutes     status
0        D101     Sato               35  Delivered
1        D102   Tanaka               62  Delivered
2        D103     Sato           eighty       Late
3        D104   Tanaka               -5  Delivered
4        D105  Unknown               48       Late
6        D106   Suzuki              NaN  Delivered

In [7]:
df["delivery_minutes"] = df["delivery_minutes"].replace({"-5":"5", "eighty":"80"})
df

C:\Users\sho_taso\AppData\Local\Temp\ipykernel_12784\430557957.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["delivery_minutes"] = df["delivery_minutes"].replace({"-5":"5", "eighty":"80"})

  delivery_id  courier delivery_minutes     status
0        D101     Sato               35  Delivered
1        D102   Tanaka               62  Delivered
2        D103     Sato               80       Late
3        D104   Tanaka                5  Delivered
4        D105  Unknown               48       Late
6        D106   Suzuki              NaN  Delivered

In [8]:
df["delivery_minutes"] = pd.to_numeric(df["delivery_minutes"])
df

C:\Users\sho_taso\AppData\Local\Temp\ipykernel_12784\1271271620.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["delivery_minutes"] = pd.to_numeric(df["delivery_minutes"])

  delivery_id  courier  delivery_minutes     status
0        D101     Sato              35.0  Delivered
1        D102   Tanaka              62.0  Delivered
2        D103     Sato              80.0       Late
3        D104   Tanaka               5.0  Delivered
4        D105  Unknown              48.0       Late
6        D106   Suzuki               NaN  Delivered

In [9]:
df["delivery_minutes"] = df["delivery_minutes"].fillna(0)

C:\Users\sho_taso\AppData\Local\Temp\ipykernel_12784\485262376.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["delivery_minutes"] = df["delivery_minutes"].fillna(0)

In [10]:
df.to_csv('cleaneddata.csv')

In [11]:
df1 = pd.read_csv('postgredata.csv')
df1

  delivery_id region promised_date delivered_date  order_value
0        D101   East    2026-08-20     2026-08-20         4200
1        D102   West    2026-08-20     2026-08-22         3100
2        D103   East    2026-08-21     2026-08-23         5600
3        D104   West    2026-08-22     2026-08-22         2800
4        D105   East    2026-08-23     2026-08-24         3900
5        D106  North    2026-08-23     2026-08-23         4700

In [12]:
total_df = pd.merge(df, df1, on="delivery_id", how="inner")
total_df

,delivery_id,courier,delivery_minutes,status,region,promised_date,delivered_date,order_value
0,D101,Sato,35.0,Delivered,East,2026-08-20,2026-08-20,4200
1,D102,Tanaka,62.0,Delivered,West,2026-08-20,2026-08-22,3100
2,D103,Sato,80.0,Late,East,2026-08-21,2026-08-23,5600
3,D104,Tanaka,5.0,Delivered,West,2026-08-22,2026-08-22,2800
4,D105,Unknown,48.0,Late,East,2026-08-23,2026-08-24,3900
5,D106,Suzuki,0.0,Delivered,North,2026-08-23,2026-08-23,4700

In [13]:
total_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6 entries, 0 to 5
Data columns (total 8 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   delivery_id       6 non-null      object
 1   courier           6 non-null      object
 2   delivery_minutes  6 non-null      float64
 3   status            6 non-null      object
 4   region            6 non-null      object
 5   promised_date     6 non-null      object
 6   delivered_date    6 non-null      object
 7   order_value       6 non-null      int64
dtypes: float64(1), int64(1), object(6)
memory usage: 516.0+ bytes

In [14]:
total_df = total_df.astype({"promised_date":"datetime64[ns]","delivered_date":"datetime64[ns]" })
total_df

,delivery_id,courier,delivery_minutes,status,region,promised_date,delivered_date,order_value
0,D101,Sato,35.0,Delivered,East,2026-08-20,2026-08-20,4200
1,D102,Tanaka,62.0,Delivered,West,2026-08-20,2026-08-22,3100
2,D103,Sato,80.0,Late,East,2026-08-21,2026-08-23,5600
3,D104,Tanaka,5.0,Delivered,West,2026-08-22,2026-08-22,2800
4,D105,Unknown,48.0,Late,East,2026-08-23,2026-08-24,3900
5,D106,Suzuki,0.0,Delivered,North,2026-08-23,2026-08-23,4700

In [15]:
total_df.to_csv("conpletedata.csv")