In [13]:
import pandas as pd
import numpy as np

In [14]:
df = pd.read_csv('data.csv')
df

  product_id        supplier delivery_date units_received unit_cost
0       P101    North Supply     2026/10/1             20     1,200
1       P102   north supply     01/10/2026             50       300
2       P103      East Goods     2026/10/2            ten       850
3       P104      EAST GOODS       invalid             -5      1500
4       P105             NaN     2026/10/4             30   unknown
5       P105             NaN     2026/10/4             30   unknown

In [15]:
df.drop_duplicates(inplace=True)

In [16]:
df["delivery_date"] = df["delivery_date"].replace("invalid",None).pipe(pd.to_datetime, format="mixed")
df

  product_id        supplier delivery_date units_received unit_cost
0       P101    North Supply    2026-10-01             20     1,200
1       P102   north supply     2026-01-10             50       300
2       P103      East Goods    2026-10-02            ten       850
3       P104      EAST GOODS           NaT             -5      1500
4       P105             NaN    2026-10-04             30   unknown

In [17]:
df["supplier"] = df["supplier"].str.strip().str.capitalize()
df

  product_id      supplier delivery_date units_received unit_cost
0       P101  North supply    2026-10-01             20     1,200
1       P102  North supply    2026-01-10             50       300
2       P103    East goods    2026-10-02            ten       850
3       P104    East goods           NaT             -5      1500
4       P105           NaN    2026-10-04             30   unknown

In [18]:
df["units_received"] = df["units_received"].replace({"ten":10,"-":""},regex=True).pipe(pd.to_numeric)
df

  product_id      supplier delivery_date  units_received unit_cost
0       P101  North supply    2026-10-01              20     1,200
1       P102  North supply    2026-01-10              50       300
2       P103    East goods    2026-10-02              10       850
3       P104    East goods           NaT               5      1500
4       P105           NaN    2026-10-04              30   unknown

In [19]:
df["unit_cost"] = df["unit_cost"].replace({"unknown":None,",":""},regex=True).apply(pd.to_numeric,errors = 'coerce')
df

  product_id      supplier delivery_date  units_received  unit_cost
0       P101  North supply    2026-10-01              20     1200.0
1       P102  North supply    2026-01-10              50      300.0
2       P103    East goods    2026-10-02              10      850.0
3       P104    East goods           NaT               5     1500.0
4       P105           NaN    2026-10-04              30        NaN

In [20]:
df["data_issue"] = df[
    ["supplier", "delivery_date", "unit_cost"]
].isna().any(axis=1)
df

,product_id,supplier,delivery_date,units_received,unit_cost,data_issue
0,P101,North supply,2026-10-01,20,1200.0,False
1,P102,North supply,2026-01-10,50,300.0,False
2,P103,East goods,2026-10-02,10,850.0,False
3,P104,East goods,NaT,5,1500.0,True
4,P105,NaN,2026-10-04,30,NaN,True

In [21]:
df2 = pd.read_csv("data2.csv")
df2

  product_id  product_name   category  stock_quantity
0       P101  Laptop Stand     Office              12
1       P102     USB Cable       Tech              40
2       P103     Desk Lamp     Office               5
3       P104    Headphones       Tech               0
4       P105  Water Bottle  Lifestyle              20

In [22]:
df3 = pd.read_csv("data3.csv")
df3

  sale_id product_id  quantity
0    S001       P101         8
1    S002       P101         4
2    S003       P102        10
3    S004       P103        15
4    S005       P104         6

In [23]:
all_df = pd.merge(pd.merge(df,df2,on="product_id",how="outer"),df3,on="product_id", how="outer")
all_df

,product_id,supplier,delivery_date,units_received,unit_cost,data_issue,product_name,category,stock_quantity,sale_id,quantity
0,P101,North supply,2026-10-01,20,1200.0,False,Laptop Stand,Office,12,S001,8.0
1,P101,North supply,2026-10-01,20,1200.0,False,Laptop Stand,Office,12,S002,4.0
2,P102,North supply,2026-01-10,50,300.0,False,USB Cable,Tech,40,S003,10.0
3,P103,East goods,2026-10-02,10,850.0,False,Desk Lamp,Office,5,S004,15.0
4,P104,East goods,NaT,5,1500.0,True,Headphones,Tech,0,S005,6.0
5,P105,NaN,2026-10-04,30,NaN,True,Water Bottle,Lifestyle,20,NaN,NaN

In [24]:
all_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6 entries, 0 to 5
Data columns (total 11 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   product_id      6 non-null      object
 1   supplier        5 non-null      object
 2   delivery_date   5 non-null      datetime64[ns]
 3   units_received  6 non-null      int64
 4   unit_cost       5 non-null      float64
 5   data_issue      6 non-null      bool
 6   product_name    6 non-null      object
 7   category        6 non-null      object
 8   stock_quantity  6 non-null      int64
 9   sale_id         5 non-null      object
 10  quantity        5 non-null      float64
dtypes: bool(1), datetime64[ns](1), float64(2), int64(2), object(5)
memory usage: 618.0+ bytes

In [25]:
all_df.to_csv('complete_data.csv')