In [129]:
import pandas as pd
import numpy as np

In [130]:
df = pd.read_csv('data.csv')
df

  product_id        supplier delivery_date units_received unit_cost
0       P101    North Supply     2026/10/1             20     1,200
1       P102   north supply     01/10/2026             50       300
2       P103      East Goods     2026/10/2            ten       850
3       P104      EAST GOODS       invalid             -5      1500
4       P105             NaN     2026/10/4             30   unknown
5       P105             NaN     2026/10/4             30   unknown

In [131]:
df.drop_duplicates(inplace=True)

In [132]:
df["delivery_date"] = df["delivery_date"].replace("invalid",None).pipe(pd.to_datetime, format="mixed")
df

  product_id        supplier delivery_date units_received unit_cost
0       P101    North Supply    2026-10-01             20     1,200
1       P102   north supply     2026-01-10             50       300
2       P103      East Goods    2026-10-02            ten       850
3       P104      EAST GOODS           NaT             -5      1500
4       P105             NaN    2026-10-04             30   unknown

In [133]:
df["supplier"] = df["supplier"].str.strip().str.capitalize()
df

  product_id      supplier delivery_date units_received unit_cost
0       P101  North supply    2026-10-01             20     1,200
1       P102  North supply    2026-01-10             50       300
2       P103    East goods    2026-10-02            ten       850
3       P104    East goods           NaT             -5      1500
4       P105           NaN    2026-10-04             30   unknown

In [134]:
df["units_received"] = df["units_received"].replace({"ten":10,"-":""},regex=True).pipe(pd.to_numeric)
df

  product_id      supplier delivery_date  units_received unit_cost
0       P101  North supply    2026-10-01              20     1,200
1       P102  North supply    2026-01-10              50       300
2       P103    East goods    2026-10-02              10       850
3       P104    East goods           NaT               5      1500
4       P105           NaN    2026-10-04              30   unknown

In [135]:
df["unit_cost"] = df["unit_cost"].replace({"unknown":None,",":""},regex=True).apply(pd.to_numeric,errors = 'coerce')
df

  product_id      supplier delivery_date  units_received  unit_cost
0       P101  North supply    2026-10-01              20     1200.0
1       P102  North supply    2026-01-10              50      300.0
2       P103    East goods    2026-10-02              10      850.0
3       P104    East goods           NaT               5     1500.0
4       P105           NaN    2026-10-04              30        NaN

In [136]:
df["data_issue"] = df[
    ["supplier", "delivery_date", "unit_cost"]
].isna().any(axis=1)
df

,product_id,supplier,delivery_date,units_received,unit_cost,data_issue
0,P101,North supply,2026-10-01,20,1200.0,False
1,P102,North supply,2026-01-10,50,300.0,False
2,P103,East goods,2026-10-02,10,850.0,False
3,P104,East goods,NaT,5,1500.0,True
4,P105,NaN,2026-10-04,30,NaN,True