In [186]:
import pandas as pd
import numpy as np

In [187]:
df =pd.read_csv('../Datasets/sales_superstore_raw.csv')
df

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country/Region,City,...,Postal Code,Region,Product ID,Category,Sub-Category,Product Name,Sales,Quantity,Discount,Profit
0,1,US-2023-103800,03.01.2023,2023-01-07,Standard Class,DP-13000,Darren Powers,Consumer,United States,Houston,...,77095,Central,OFF-PA-10000174,Office Supplies,Paper,"Message Book, Wirebound, Four 5 1/2"" X 4"" Form...",NaN,2.0,0.2,5.5512
1,2,US-2023-112326,04-Jan-2023,2023-01-08,Standard Class,PO-19195,Phillina Ober,Home Office,United States,Naperville,...,60540,Central,OFF-BI-10004094,Office Supplies,Binders,GBC Standard Plastic Binding Systems Combs,3.540,2.0,0.8,NaN
2,3,US-2023-112326,2023-01-04 00:00:00,2023-01-08,Standard Class,PO-19195,Phillina Ober,home office,United States,Naperville,...,60540,Central,OFF-LA-10003223,Office Supplies,Labels,Avery 508,11.784,3.0,0.2,4.2717
3,4,US-2023-112326,2023-01-04 00:00:00,2023-01-08,Standard Class,PO-19195,Phillina Ober,Home Office,United States,Naperville,...,60540,Central,OFF-ST-10002743,Office Supplies,Storage,SAFCO Boltless Steel Shelving,NaN,3.0,0.2,-64.7748
4,5,US-2023-141817,2023-01-05 00:00:00,2023-01-12,NaN,MB-18085,Mick Brown,Consumer,United States,Philadelphia,...,19143,East,OFF-AR-10003478,Office Supplies,Art,Avery Hi-Liter EverBold Pen Style Fluorescent ...,19.536,3.0,0.2,4.8840
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10698,10190,US-2026-143259,2026-12-30 00:00:00,2027-01-03,Standard Class,PO-18865,Patrick O'Donnell,Consumer,United States,New York City,...,10009,East,OFF-BI-10003684,Office Supplies,Binders,Wilson Jones Legal Size Ring Binders,52.776,3.0,0.2,19.7910
10699,10191,US-2026-115427,2026-12-30 00:00:00,2027-01-03,Standard Class,EB-13975,Erica Bern,Corporate,United States,Fairfield,...,94533,West,OFF-BI-10004632,Office Supplies,Binders,GBC Binding covers,20.720,2.0,0.2,6.4750
10700,10192,US-2026-156720,20261230,2027-01-03,Standard Class,JM-15580,Jill Matthias,Consumer,United States,Loveland,...,80538,West,OFF-FA-10003472,Office Supplies,Fasteners,Bagged Rubber Bands,3.024,3.0,0.2,-0.6048
10701,10193,US-2026-143259,30.12.2026,2027-01-03,Standard Class,PO-18865,Patrick O'Donnell,Consumer,United States,New York City,...,10009,East,TEC-PH-10004774,Technology,Phones,Gear Head AU3700S Headset,90.930,7.0,0.0,2.7279
10702,10194,CA-2026-143500,30.12.2026,2027-01-03,Standard Class,HO-15230,Harry Olson,Consumer,Canada,Charlottetown,...,C0A,East,OFF-BI-10004040,Office Supplies,Binders,Wilson Jones Impact Binders,3.024,3.0,0.2,-0.6048

In [188]:
df.isnull().sum()

Row ID               0
Order ID             0
Order Date           0
Ship Date            0
Ship Mode         1071
Customer ID          0
Customer Name        0
Segment              0
Country/Region       0
City                 0
State/Province       0
Postal Code          0
Region               0
Product ID           0
Category             0
Sub-Category         0
Product Name         0
Sales             2038
Quantity           537
Discount             0
Profit            1076
dtype: int64

In [189]:
print(df.dtypes)

Row ID              int64
Order ID           object
Order Date         object
Ship Date          object
Ship Mode          object
Customer ID        object
Customer Name      object
Segment            object
Country/Region     object
City               object
State/Province     object
Postal Code        object
Region             object
Product ID         object
Category           object
Sub-Category       object
Product Name       object
Sales             float64
Quantity          float64
Discount          float64
Profit            float64
dtype: object

In [190]:
df['Order Date'] = pd.to_datetime(df['Order Date'], format='mixed').dt.strftime('%Y-%m-%d')
df

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country/Region,City,...,Postal Code,Region,Product ID,Category,Sub-Category,Product Name,Sales,Quantity,Discount,Profit
0,1,US-2023-103800,2023-03-01,2023-01-07,Standard Class,DP-13000,Darren Powers,Consumer,United States,Houston,...,77095,Central,OFF-PA-10000174,Office Supplies,Paper,"Message Book, Wirebound, Four 5 1/2"" X 4"" Form...",NaN,2.0,0.2,5.5512
1,2,US-2023-112326,2023-01-04,2023-01-08,Standard Class,PO-19195,Phillina Ober,Home Office,United States,Naperville,...,60540,Central,OFF-BI-10004094,Office Supplies,Binders,GBC Standard Plastic Binding Systems Combs,3.540,2.0,0.8,NaN
2,3,US-2023-112326,2023-01-04,2023-01-08,Standard Class,PO-19195,Phillina Ober,home office,United States,Naperville,...,60540,Central,OFF-LA-10003223,Office Supplies,Labels,Avery 508,11.784,3.0,0.2,4.2717
3,4,US-2023-112326,2023-01-04,2023-01-08,Standard Class,PO-19195,Phillina Ober,Home Office,United States,Naperville,...,60540,Central,OFF-ST-10002743,Office Supplies,Storage,SAFCO Boltless Steel Shelving,NaN,3.0,0.2,-64.7748
4,5,US-2023-141817,2023-01-05,2023-01-12,NaN,MB-18085,Mick Brown,Consumer,United States,Philadelphia,...,19143,East,OFF-AR-10003478,Office Supplies,Art,Avery Hi-Liter EverBold Pen Style Fluorescent ...,19.536,3.0,0.2,4.8840
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10698,10190,US-2026-143259,2026-12-30,2027-01-03,Standard Class,PO-18865,Patrick O'Donnell,Consumer,United States,New York City,...,10009,East,OFF-BI-10003684,Office Supplies,Binders,Wilson Jones Legal Size Ring Binders,52.776,3.0,0.2,19.7910
10699,10191,US-2026-115427,2026-12-30,2027-01-03,Standard Class,EB-13975,Erica Bern,Corporate,United States,Fairfield,...,94533,West,OFF-BI-10004632,Office Supplies,Binders,GBC Binding covers,20.720,2.0,0.2,6.4750
10700,10192,US-2026-156720,2026-12-30,2027-01-03,Standard Class,JM-15580,Jill Matthias,Consumer,United States,Loveland,...,80538,West,OFF-FA-10003472,Office Supplies,Fasteners,Bagged Rubber Bands,3.024,3.0,0.2,-0.6048
10701,10193,US-2026-143259,2026-12-30,2027-01-03,Standard Class,PO-18865,Patrick O'Donnell,Consumer,United States,New York City,...,10009,East,TEC-PH-10004774,Technology,Phones,Gear Head AU3700S Headset,90.930,7.0,0.0,2.7279
10702,10194,CA-2026-143500,2026-12-30,2027-01-03,Standard Class,HO-15230,Harry Olson,Consumer,Canada,Charlottetown,...,C0A,East,OFF-BI-10004040,Office Supplies,Binders,Wilson Jones Impact Binders,3.024,3.0,0.2,-0.6048

In [191]:
print(df.dtypes)

Row ID              int64
Order ID           object
Order Date         object
Ship Date          object
Ship Mode          object
Customer ID        object
Customer Name      object
Segment            object
Country/Region     object
City               object
State/Province     object
Postal Code        object
Region             object
Product ID         object
Category           object
Sub-Category       object
Product Name       object
Sales             float64
Quantity          float64
Discount          float64
Profit            float64
dtype: object

In [192]:
df['Ship Mode'] = df['Ship Mode'].fillna('Unknown')
df

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country/Region,City,...,Postal Code,Region,Product ID,Category,Sub-Category,Product Name,Sales,Quantity,Discount,Profit
0,1,US-2023-103800,2023-03-01,2023-01-07,Standard Class,DP-13000,Darren Powers,Consumer,United States,Houston,...,77095,Central,OFF-PA-10000174,Office Supplies,Paper,"Message Book, Wirebound, Four 5 1/2"" X 4"" Form...",NaN,2.0,0.2,5.5512
1,2,US-2023-112326,2023-01-04,2023-01-08,Standard Class,PO-19195,Phillina Ober,Home Office,United States,Naperville,...,60540,Central,OFF-BI-10004094,Office Supplies,Binders,GBC Standard Plastic Binding Systems Combs,3.540,2.0,0.8,NaN
2,3,US-2023-112326,2023-01-04,2023-01-08,Standard Class,PO-19195,Phillina Ober,home office,United States,Naperville,...,60540,Central,OFF-LA-10003223,Office Supplies,Labels,Avery 508,11.784,3.0,0.2,4.2717
3,4,US-2023-112326,2023-01-04,2023-01-08,Standard Class,PO-19195,Phillina Ober,Home Office,United States,Naperville,...,60540,Central,OFF-ST-10002743,Office Supplies,Storage,SAFCO Boltless Steel Shelving,NaN,3.0,0.2,-64.7748
4,5,US-2023-141817,2023-01-05,2023-01-12,Unknown,MB-18085,Mick Brown,Consumer,United States,Philadelphia,...,19143,East,OFF-AR-10003478,Office Supplies,Art,Avery Hi-Liter EverBold Pen Style Fluorescent ...,19.536,3.0,0.2,4.8840
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10698,10190,US-2026-143259,2026-12-30,2027-01-03,Standard Class,PO-18865,Patrick O'Donnell,Consumer,United States,New York City,...,10009,East,OFF-BI-10003684,Office Supplies,Binders,Wilson Jones Legal Size Ring Binders,52.776,3.0,0.2,19.7910
10699,10191,US-2026-115427,2026-12-30,2027-01-03,Standard Class,EB-13975,Erica Bern,Corporate,United States,Fairfield,...,94533,West,OFF-BI-10004632,Office Supplies,Binders,GBC Binding covers,20.720,2.0,0.2,6.4750
10700,10192,US-2026-156720,2026-12-30,2027-01-03,Standard Class,JM-15580,Jill Matthias,Consumer,United States,Loveland,...,80538,West,OFF-FA-10003472,Office Supplies,Fasteners,Bagged Rubber Bands,3.024,3.0,0.2,-0.6048
10701,10193,US-2026-143259,2026-12-30,2027-01-03,Standard Class,PO-18865,Patrick O'Donnell,Consumer,United States,New York City,...,10009,East,TEC-PH-10004774,Technology,Phones,Gear Head AU3700S Headset,90.930,7.0,0.0,2.7279
10702,10194,CA-2026-143500,2026-12-30,2027-01-03,Standard Class,HO-15230,Harry Olson,Consumer,Canada,Charlottetown,...,C0A,East,OFF-BI-10004040,Office Supplies,Binders,Wilson Jones Impact Binders,3.024,3.0,0.2,-0.6048

In [193]:
df.isnull().sum()

Row ID               0
Order ID             0
Order Date           0
Ship Date            0
Ship Mode            0
Customer ID          0
Customer Name        0
Segment              0
Country/Region       0
City                 0
State/Province       0
Postal Code          0
Region               0
Product ID           0
Category             0
Sub-Category         0
Product Name         0
Sales             2038
Quantity           537
Discount             0
Profit            1076
dtype: int64

In [194]:
df['Segment'].unique()

array(['Consumer', 'Home Office', 'home office', 'Corporate', 'Consumr',
       'Corporate  ', 'consumer', 'Counsumer', 'Corp.', '  Consumer',
       'corporate', 'Home office', 'Home-Office', 'Corperate',
       'HomeOffice'], dtype=object)

In [195]:
df['Segment'] = df['Segment'].str.title()
df['Segment'].unique()

array(['Consumer', 'Home Office', 'Corporate', 'Consumr', 'Corporate  ',
       'Counsumer', 'Corp.', '  Consumer', 'Home-Office', 'Corperate',
       'Homeoffice'], dtype=object)

In [196]:
df['Segment'] = df['Segment'].replace(['Consumr','Counsumer','  Consumer'], 'Consumer')
df['Segment'].unique()

array(['Consumer', 'Home Office', 'Corporate', 'Corporate  ', 'Corp.',
       'Home-Office', 'Corperate', 'Homeoffice'], dtype=object)

In [197]:
df['Segment'] = df['Segment'].replace(['Home-Office','Homeoffice'], 'Home Office')
df['Segment'].unique()

array(['Consumer', 'Home Office', 'Corporate', 'Corporate  ', 'Corp.',
       'Corperate'], dtype=object)

In [198]:
df['Segment'] = df['Segment'].replace(['Corporate  ','Corp.','Corperate'], 'Corporate')
df['Segment'].unique()

array(['Consumer', 'Home Office', 'Corporate'], dtype=object)

In [199]:
df

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country/Region,City,...,Postal Code,Region,Product ID,Category,Sub-Category,Product Name,Sales,Quantity,Discount,Profit
0,1,US-2023-103800,2023-03-01,2023-01-07,Standard Class,DP-13000,Darren Powers,Consumer,United States,Houston,...,77095,Central,OFF-PA-10000174,Office Supplies,Paper,"Message Book, Wirebound, Four 5 1/2"" X 4"" Form...",NaN,2.0,0.2,5.5512
1,2,US-2023-112326,2023-01-04,2023-01-08,Standard Class,PO-19195,Phillina Ober,Home Office,United States,Naperville,...,60540,Central,OFF-BI-10004094,Office Supplies,Binders,GBC Standard Plastic Binding Systems Combs,3.540,2.0,0.8,NaN
2,3,US-2023-112326,2023-01-04,2023-01-08,Standard Class,PO-19195,Phillina Ober,Home Office,United States,Naperville,...,60540,Central,OFF-LA-10003223,Office Supplies,Labels,Avery 508,11.784,3.0,0.2,4.2717
3,4,US-2023-112326,2023-01-04,2023-01-08,Standard Class,PO-19195,Phillina Ober,Home Office,United States,Naperville,...,60540,Central,OFF-ST-10002743,Office Supplies,Storage,SAFCO Boltless Steel Shelving,NaN,3.0,0.2,-64.7748
4,5,US-2023-141817,2023-01-05,2023-01-12,Unknown,MB-18085,Mick Brown,Consumer,United States,Philadelphia,...,19143,East,OFF-AR-10003478,Office Supplies,Art,Avery Hi-Liter EverBold Pen Style Fluorescent ...,19.536,3.0,0.2,4.8840
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10698,10190,US-2026-143259,2026-12-30,2027-01-03,Standard Class,PO-18865,Patrick O'Donnell,Consumer,United States,New York City,...,10009,East,OFF-BI-10003684,Office Supplies,Binders,Wilson Jones Legal Size Ring Binders,52.776,3.0,0.2,19.7910
10699,10191,US-2026-115427,2026-12-30,2027-01-03,Standard Class,EB-13975,Erica Bern,Corporate,United States,Fairfield,...,94533,West,OFF-BI-10004632,Office Supplies,Binders,GBC Binding covers,20.720,2.0,0.2,6.4750
10700,10192,US-2026-156720,2026-12-30,2027-01-03,Standard Class,JM-15580,Jill Matthias,Consumer,United States,Loveland,...,80538,West,OFF-FA-10003472,Office Supplies,Fasteners,Bagged Rubber Bands,3.024,3.0,0.2,-0.6048
10701,10193,US-2026-143259,2026-12-30,2027-01-03,Standard Class,PO-18865,Patrick O'Donnell,Consumer,United States,New York City,...,10009,East,TEC-PH-10004774,Technology,Phones,Gear Head AU3700S Headset,90.930,7.0,0.0,2.7279
10702,10194,CA-2026-143500,2026-12-30,2027-01-03,Standard Class,HO-15230,Harry Olson,Consumer,Canada,Charlottetown,...,C0A,East,OFF-BI-10004040,Office Supplies,Binders,Wilson Jones Impact Binders,3.024,3.0,0.2,-0.6048

In [200]:
df['Country/Region'].unique()

array(['United States', 'Canada'], dtype=object)

In [201]:
df['City'].unique()

array(['Houston', 'Naperville', 'Philadelphia', 'Henderson', 'Athens',
       'Los Angeles', 'Huntsville', 'Laredo', 'Springfield', 'Dover',
       'San Francisco', 'Mount Pleasant', 'Newark', 'Bossier City',
       'Roswell', 'Scottsdale', 'Jonesboro', 'Westland', 'Smyrna',
       'Miami', 'Toronto', 'Lafayette', 'Las Vegas', 'Rapid City',
       'Alexandria', 'San Diego', 'New York City', 'Detroit',
       'Mission Viejo', 'Green Bay', 'Saint Petersburg', 'Seattle',
       'Escondido', 'Romeoville', 'Chesapeake', 'Linden',
       'North Las Vegas', 'Columbia', 'Concord', 'Dallas', 'Chicago',
       'Lubbock', 'Arlington', 'Richmond', 'Woodstock', 'Moreno Valley',
       'El Paso', 'Medford', 'Columbus', 'Elmhurst', 'Wilmington',
       'Margate', 'Yonkers', 'Des Moines', 'Denver', 'Royal Oak',
       'Roseville', 'Calgary', 'Huntington Beach', 'Logan',
       'Jacksonville', 'Tampa', 'Raleigh', 'Lakeville', 'Jackson',
       'Burbank', 'Lakeland', 'Knoxville', 'Hamilton', 'Asheville',
       'Tucson', 'Portage', 'Greensboro', 'Delray Beach', 'Fresno',
       'Pomona', 'Albuquerque', 'Plano', 'Brownsville', 'Long Beach',
       'Apple Valley', 'Vallejo', 'Revere', 'Virginia Beach',
       'Dearborn Heights', 'Decatur', 'Lancaster', 'Mobile', 'Marietta',
       'Toledo', 'Glendale', 'Chandler', 'Lewiston', 'Great Falls',
       'Austin', 'Redondo Beach', 'Lodi', 'Bloomington', 'Baltimore',
       'San Jose', 'Troy', 'San Gabriel', 'Jamestown', 'Memphis',
       'Lake Charles', 'Rochester', 'Louisville', 'Appleton',
       'Middletown', 'San Antonio', 'Freeport', 'Lawrence', 'Kent',
       'Fort Worth', 'Watertown', 'Milwaukee', 'Franklin', 'Hialeah',
       'West Jordan', 'Oakland', 'Eau Claire', 'Akron', 'Cleveland',
       'Midland', 'San Marcos', 'Vancouver', 'Montreal', 'Bellevue',
       'Murray', 'Buffalo Grove', 'Little Rock', 'Lakewood', 'Orem',
       'Aurora', 'Peoria', 'Bristol', 'Harrisonburg', 'Mishawaka',
       'Hempstead', 'Halifax', 'Lawton', 'Waynesboro', 'Meriden',
       'Pueblo', 'Chester', 'Phoenix', 'Minneapolis', 'Salem',
       'Southaven', 'Cincinnati', 'Deltona', 'Plainfield', 'Palm Coast',
       'El Cajon', 'Buffalo', 'Hackensack', 'Niagara Falls',
       'League City', 'Sioux Falls', 'New Rochelle', 'Riverside', 'Omaha',
       'Atlanta', 'Draper', 'Apopka', 'Charlotte', 'Bangor',
       'Pleasant Grove', 'Texas City', 'Trenton', 'Vacaville',
       'Hollywood', 'Fairfield', 'Hampton', 'Saint Charles',
       'North Miami', 'Grand Rapids', 'Oceanside', 'Billings',
       'Owensboro', 'Santa Fe', 'Fayetteville', 'Bowling Green', 'Tulsa',
       'Oswego', 'Santa Clara', 'Pasco', 'Tyler', 'Macon', 'Lowell',
       'Greenville', 'Gresham', 'Clifton', 'Oxnard', 'Olathe', 'Cary',
       'Odessa', 'Tempe', 'Corpus Christi', 'Chula Vista', 'Garland',
       'Boca Raton', 'Mesquite', 'Clarksville', 'Boynton Beach', 'Reno',
       'Evanston', 'Durham', 'Edmonton', 'Indianapolis', 'Manteca',
       'Pasadena', 'Edmonds', 'Mount Vernon', 'Everett', 'Parma',
       'Beaumont', 'Montgomery', 'Texarkana', 'Newport News',
       'Rancho Cucamonga', 'Rock Hill', 'Fort Lauderdale', 'Garden City',
       'Cranston', 'Lorain', 'Avondale', 'Mason', 'Orange', 'Portland',
       'Medina', 'Irving', 'Nashville', 'Wausau', 'Redding', 'Reading',
       'Madison', 'Carrollton', 'Johnson City', 'Manhattan', 'Moorhead',
       'Cedar Hill', 'Des Plaines', 'Provo', 'Salt Lake City',
       'Coon Rapids', 'Monroe', 'Bolingbrook', 'Sacramento',
       'Saint Louis', "St. John's", 'Woonsocket', 'Brentwood', 'Utica',
       'Tigard', 'Skokie', 'Orlando', 'Clinton', 'Sandy Springs',
       'Moncton', 'Oklahoma City', 'Gilbert', 'Olympia', 'Mesa',
       'Caldwell', 'Marion', 'Florence', 'Grand Prairie', 'Thornton',
       'Port Arthur', 'Colorado Springs', 'Beverly', 'Anaheim',
       'Cottage Grove', 'Quebec City', 'Taylor', 'Charlottetown',
       'Providence', 'Baytown', 'Woodbury', 'Park Ridge', 'Bartlett',
       'Bozeman', 'West Palm Beach', 'Rome', 'Suffolk', 'Kenosha',
       'Perth Amboy', 'Hot Springs', 'Las Cruces', 'Sterling Heights',
       'Leominster', 'Altoona', 'Coppell', 'Bethlehem', 'New Castle',
       'Plantation', 'Chico', 'Lehi', 'Auburn', 'San Bernardino',
       'Thousand Oaks', 'Covington', 'Coral Springs', 'Normal', 'Lansing',
       'Spokane', 'Norwich', 'Norfolk', 'Farmington', 'Mcallen',
       'New Albany', 'Santa Maria', 'Daytona Beach', 'Washington',
       'Tinley Park', 'Allen', 'Cuyahoga Falls', 'Camarillo', 'Wilson',
       'Frankfort', 'Wichita', 'Haltom City', 'Manchester', 'Paterson',
       'Pocatello', 'Layton', 'East Point', 'Carol Stream', 'Holyoke',
       'Vineland', 'Amarillo', 'Bakersfield', 'Port Saint Lucie',
       'Highland Park', 'South Bend', 'Hattiesburg', 'Kirkwood', 'Boise',
       'Redmond', 'Eagan', 'Yucaipa', 'New Bedford', 'Allentown',
       'Murrieta', 'Bedford', 'Holland', 'Charlottesville', 'Tamarac',
       'La Quinta', 'Redlands', 'North Charleston', 'Lincoln Park',
       'Quincy', 'Dubuque', 'Broken Arrow', 'Rockford', 'Murfreesboro',
       'Bayonne', 'Cambridge', 'Hillsboro', 'Rockville', 'Warner Robins',
       'Ann Arbor', 'Santa Barbara', 'Noblesville', 'Orland Park',
       'Sparks', 'Salinas', 'Conway', 'Burlington', 'Helena', 'Lebanon',
       'Rio Rancho', 'Frisco', 'Morristown', 'Lake Elsinore',
       'Pembroke Pines', 'Champaign', 'Dearborn', 'Santa Ana',
       'Tallahassee', 'Temecula', 'Costa Mesa', 'Glenview',
       'Bullhead City', 'Lindenhurst', 'Superior', 'Dublin', 'Visalia',
       'Missoula', 'Gaithersburg', 'Longview', 'Westfield', 'Gulfport',
       'Atlantic City', 'Sierra Vista', 'Chattanooga', 'Belleville',
       'La Crosse', 'Round Rock', 'Andover', 'Milford', 'Harlingen',
       'Redwood City', 'Bryan', 'Malden', 'Littleton', 'Saint Peters',
       'Norman', 'Grapevine', 'Gastonia', 'Jefferson City',
       'San Clemente', 'Hesperia', 'Encinitas', 'Yuma', 'Waterbury',
       'Warwick', 'Passaic', 'Parker', 'Longmont', 'York', 'Broomfield',
       'Winnipeg', 'Pensacola', 'Hendersonville', 'West Allis', 'Kenner',
       'Davis', 'Edinburg', 'Fort Collins', 'Pharr', 'Sheboygan',
       'Englewood', 'Waco', 'Waukesha', 'Georgetown', 'Cedar Rapids',
       'Saint Paul', 'Thomasville', 'Wheeling', 'Stockton', 'Arvada',
       'Twin Falls', 'Laguna Niguel', 'Marlborough', 'Woodland', 'Regina',
       'Iowa City', 'La Porte', 'Lake Forest', 'Coral Gables',
       'The Colony', 'Marysville', 'Bridgeton', 'San Luis Obispo',
       'Conroe', 'Urbandale', 'Eugene', 'Cheyenne', 'Arlington Heights',
       'Carlsbad', 'Edmond', 'Montebello', 'Shelton', 'East Orange',
       'Overland Park', 'Hickory', 'San Angelo', 'Morgan Hill', 'Antioch',
       'Richardson', 'Fremont', 'Greenwood', 'Homestead', 'Torrance',
       'Goldsboro', 'Nashua', 'Deer Park', 'Tuscaloosa', 'Ormond Beach',
       'Keller', 'Hoover', 'Muskogee', 'Rogers', 'Pompano Beach',
       'Oak Park', 'New Brunswick', 'Greeley', 'Kissimmee', 'Sanford',
       'Danville', 'Westminster', 'Mansfield', 'Fargo', 'Laurel',
       'Bellingham', 'Missouri City', 'Pearland', 'Rochester Hills',
       'Maple Grove', 'Chapel Hill', 'Commerce City', 'Citrus Heights',
       'Pico Rivera', 'San Mateo', 'Waterloo', 'Elkhart', 'Loveland',
       'Inglewood', 'La Mesa', 'Modesto', 'Independence', 'Clovis',
       'Grand Island', 'Melbourne', 'Pine Bluff', 'Saint Cloud',
       'Miramar', 'Mentor', 'Meridian', 'Springdale', 'Sunnyvale',
       'Coachella', 'Aberdeen', 'Jupiter', 'Grove City', 'Elyria',
       'Hagerstown', 'Saginaw', 'College Station', 'Ontario', 'Renton',
       'Canton', 'Summerville', 'Gladstone', 'Whittier', 'Abilene',
       'Palatine', 'Port Orange', 'Danbury'], dtype=object)

In [202]:
df.isnull().sum()

Row ID               0
Order ID             0
Order Date           0
Ship Date            0
Ship Mode            0
Customer ID          0
Customer Name        0
Segment              0
Country/Region       0
City                 0
State/Province       0
Postal Code          0
Region               0
Product ID           0
Category             0
Sub-Category         0
Product Name         0
Sales             2038
Quantity           537
Discount             0
Profit            1076
dtype: int64

In [203]:
df

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country/Region,City,...,Postal Code,Region,Product ID,Category,Sub-Category,Product Name,Sales,Quantity,Discount,Profit
0,1,US-2023-103800,2023-03-01,2023-01-07,Standard Class,DP-13000,Darren Powers,Consumer,United States,Houston,...,77095,Central,OFF-PA-10000174,Office Supplies,Paper,"Message Book, Wirebound, Four 5 1/2"" X 4"" Form...",NaN,2.0,0.2,5.5512
1,2,US-2023-112326,2023-01-04,2023-01-08,Standard Class,PO-19195,Phillina Ober,Home Office,United States,Naperville,...,60540,Central,OFF-BI-10004094,Office Supplies,Binders,GBC Standard Plastic Binding Systems Combs,3.540,2.0,0.8,NaN
2,3,US-2023-112326,2023-01-04,2023-01-08,Standard Class,PO-19195,Phillina Ober,Home Office,United States,Naperville,...,60540,Central,OFF-LA-10003223,Office Supplies,Labels,Avery 508,11.784,3.0,0.2,4.2717
3,4,US-2023-112326,2023-01-04,2023-01-08,Standard Class,PO-19195,Phillina Ober,Home Office,United States,Naperville,...,60540,Central,OFF-ST-10002743,Office Supplies,Storage,SAFCO Boltless Steel Shelving,NaN,3.0,0.2,-64.7748
4,5,US-2023-141817,2023-01-05,2023-01-12,Unknown,MB-18085,Mick Brown,Consumer,United States,Philadelphia,...,19143,East,OFF-AR-10003478,Office Supplies,Art,Avery Hi-Liter EverBold Pen Style Fluorescent ...,19.536,3.0,0.2,4.8840
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10698,10190,US-2026-143259,2026-12-30,2027-01-03,Standard Class,PO-18865,Patrick O'Donnell,Consumer,United States,New York City,...,10009,East,OFF-BI-10003684,Office Supplies,Binders,Wilson Jones Legal Size Ring Binders,52.776,3.0,0.2,19.7910
10699,10191,US-2026-115427,2026-12-30,2027-01-03,Standard Class,EB-13975,Erica Bern,Corporate,United States,Fairfield,...,94533,West,OFF-BI-10004632,Office Supplies,Binders,GBC Binding covers,20.720,2.0,0.2,6.4750
10700,10192,US-2026-156720,2026-12-30,2027-01-03,Standard Class,JM-15580,Jill Matthias,Consumer,United States,Loveland,...,80538,West,OFF-FA-10003472,Office Supplies,Fasteners,Bagged Rubber Bands,3.024,3.0,0.2,-0.6048
10701,10193,US-2026-143259,2026-12-30,2027-01-03,Standard Class,PO-18865,Patrick O'Donnell,Consumer,United States,New York City,...,10009,East,TEC-PH-10004774,Technology,Phones,Gear Head AU3700S Headset,90.930,7.0,0.0,2.7279
10702,10194,CA-2026-143500,2026-12-30,2027-01-03,Standard Class,HO-15230,Harry Olson,Consumer,Canada,Charlottetown,...,C0A,East,OFF-BI-10004040,Office Supplies,Binders,Wilson Jones Impact Binders,3.024,3.0,0.2,-0.6048

In [204]:
df['Category'].unique()

array(['Office Supplies', 'Furniture', 'Technology', '  Furniture   '],
      dtype=object)

In [205]:
df['Category'] = df['Category'].replace('  Furniture   ', 'Furniture')
df['Category'].unique()

array(['Office Supplies', 'Furniture', 'Technology'], dtype=object)

In [206]:
df['Sub-Category'].unique()

array(['Paper', 'Binders', 'Labels', 'Storage', 'Art', 'Chairs',
       'Fasteners', 'Phones', 'Furnishings', 'Accessories', 'Bookcases',
       'Envelopes', 'Appliances', 'Tables', 'Supplies', 'Machines',
       'Copiers'], dtype=object)

In [207]:
df.isnull().sum()

Row ID               0
Order ID             0
Order Date           0
Ship Date            0
Ship Mode            0
Customer ID          0
Customer Name        0
Segment              0
Country/Region       0
City                 0
State/Province       0
Postal Code          0
Region               0
Product ID           0
Category             0
Sub-Category         0
Product Name         0
Sales             2038
Quantity           537
Discount             0
Profit            1076
dtype: int64

In [208]:
df

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country/Region,City,...,Postal Code,Region,Product ID,Category,Sub-Category,Product Name,Sales,Quantity,Discount,Profit
0,1,US-2023-103800,2023-03-01,2023-01-07,Standard Class,DP-13000,Darren Powers,Consumer,United States,Houston,...,77095,Central,OFF-PA-10000174,Office Supplies,Paper,"Message Book, Wirebound, Four 5 1/2"" X 4"" Form...",NaN,2.0,0.2,5.5512
1,2,US-2023-112326,2023-01-04,2023-01-08,Standard Class,PO-19195,Phillina Ober,Home Office,United States,Naperville,...,60540,Central,OFF-BI-10004094,Office Supplies,Binders,GBC Standard Plastic Binding Systems Combs,3.540,2.0,0.8,NaN
2,3,US-2023-112326,2023-01-04,2023-01-08,Standard Class,PO-19195,Phillina Ober,Home Office,United States,Naperville,...,60540,Central,OFF-LA-10003223,Office Supplies,Labels,Avery 508,11.784,3.0,0.2,4.2717
3,4,US-2023-112326,2023-01-04,2023-01-08,Standard Class,PO-19195,Phillina Ober,Home Office,United States,Naperville,...,60540,Central,OFF-ST-10002743,Office Supplies,Storage,SAFCO Boltless Steel Shelving,NaN,3.0,0.2,-64.7748
4,5,US-2023-141817,2023-01-05,2023-01-12,Unknown,MB-18085,Mick Brown,Consumer,United States,Philadelphia,...,19143,East,OFF-AR-10003478,Office Supplies,Art,Avery Hi-Liter EverBold Pen Style Fluorescent ...,19.536,3.0,0.2,4.8840
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10698,10190,US-2026-143259,2026-12-30,2027-01-03,Standard Class,PO-18865,Patrick O'Donnell,Consumer,United States,New York City,...,10009,East,OFF-BI-10003684,Office Supplies,Binders,Wilson Jones Legal Size Ring Binders,52.776,3.0,0.2,19.7910
10699,10191,US-2026-115427,2026-12-30,2027-01-03,Standard Class,EB-13975,Erica Bern,Corporate,United States,Fairfield,...,94533,West,OFF-BI-10004632,Office Supplies,Binders,GBC Binding covers,20.720,2.0,0.2,6.4750
10700,10192,US-2026-156720,2026-12-30,2027-01-03,Standard Class,JM-15580,Jill Matthias,Consumer,United States,Loveland,...,80538,West,OFF-FA-10003472,Office Supplies,Fasteners,Bagged Rubber Bands,3.024,3.0,0.2,-0.6048
10701,10193,US-2026-143259,2026-12-30,2027-01-03,Standard Class,PO-18865,Patrick O'Donnell,Consumer,United States,New York City,...,10009,East,TEC-PH-10004774,Technology,Phones,Gear Head AU3700S Headset,90.930,7.0,0.0,2.7279
10702,10194,CA-2026-143500,2026-12-30,2027-01-03,Standard Class,HO-15230,Harry Olson,Consumer,Canada,Charlottetown,...,C0A,East,OFF-BI-10004040,Office Supplies,Binders,Wilson Jones Impact Binders,3.024,3.0,0.2,-0.6048

In [209]:
df['Sales'] = df['Sales'].fillna(df['Sales'].median())

In [210]:
df['Quantity'] = df['Quantity'].fillna(df['Quantity'].median())
df['Quantity'] = df['Quantity'].astype(int)

In [211]:
df['Profit'] = df.groupby('Category')['Profit']\
    .transform(lambda x: x.fillna(x.median()))

In [212]:
df.isnull().sum()

Row ID            0
Order ID          0
Order Date        0
Ship Date         0
Ship Mode         0
Customer ID       0
Customer Name     0
Segment           0
Country/Region    0
City              0
State/Province    0
Postal Code       0
Region            0
Product ID        0
Category          0
Sub-Category      0
Product Name      0
Sales             0
Quantity          0
Discount          0
Profit            0
dtype: int64

In [213]:
df

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country/Region,City,...,Postal Code,Region,Product ID,Category,Sub-Category,Product Name,Sales,Quantity,Discount,Profit
0,1,US-2023-103800,2023-03-01,2023-01-07,Standard Class,DP-13000,Darren Powers,Consumer,United States,Houston,...,77095,Central,OFF-PA-10000174,Office Supplies,Paper,"Message Book, Wirebound, Four 5 1/2"" X 4"" Form...",53.920,2,0.2,5.5512
1,2,US-2023-112326,2023-01-04,2023-01-08,Standard Class,PO-19195,Phillina Ober,Home Office,United States,Naperville,...,60540,Central,OFF-BI-10004094,Office Supplies,Binders,GBC Standard Plastic Binding Systems Combs,3.540,2,0.8,6.6846
2,3,US-2023-112326,2023-01-04,2023-01-08,Standard Class,PO-19195,Phillina Ober,Home Office,United States,Naperville,...,60540,Central,OFF-LA-10003223,Office Supplies,Labels,Avery 508,11.784,3,0.2,4.2717
3,4,US-2023-112326,2023-01-04,2023-01-08,Standard Class,PO-19195,Phillina Ober,Home Office,United States,Naperville,...,60540,Central,OFF-ST-10002743,Office Supplies,Storage,SAFCO Boltless Steel Shelving,53.920,3,0.2,-64.7748
4,5,US-2023-141817,2023-01-05,2023-01-12,Unknown,MB-18085,Mick Brown,Consumer,United States,Philadelphia,...,19143,East,OFF-AR-10003478,Office Supplies,Art,Avery Hi-Liter EverBold Pen Style Fluorescent ...,19.536,3,0.2,4.8840
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10698,10190,US-2026-143259,2026-12-30,2027-01-03,Standard Class,PO-18865,Patrick O'Donnell,Consumer,United States,New York City,...,10009,East,OFF-BI-10003684,Office Supplies,Binders,Wilson Jones Legal Size Ring Binders,52.776,3,0.2,19.7910
10699,10191,US-2026-115427,2026-12-30,2027-01-03,Standard Class,EB-13975,Erica Bern,Corporate,United States,Fairfield,...,94533,West,OFF-BI-10004632,Office Supplies,Binders,GBC Binding covers,20.720,2,0.2,6.4750
10700,10192,US-2026-156720,2026-12-30,2027-01-03,Standard Class,JM-15580,Jill Matthias,Consumer,United States,Loveland,...,80538,West,OFF-FA-10003472,Office Supplies,Fasteners,Bagged Rubber Bands,3.024,3,0.2,-0.6048
10701,10193,US-2026-143259,2026-12-30,2027-01-03,Standard Class,PO-18865,Patrick O'Donnell,Consumer,United States,New York City,...,10009,East,TEC-PH-10004774,Technology,Phones,Gear Head AU3700S Headset,90.930,7,0.0,2.7279
10702,10194,CA-2026-143500,2026-12-30,2027-01-03,Standard Class,HO-15230,Harry Olson,Consumer,Canada,Charlottetown,...,C0A,East,OFF-BI-10004040,Office Supplies,Binders,Wilson Jones Impact Binders,3.024,3,0.2,-0.6048

In [214]:
df = df.drop('Product Name', axis=1)
df

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country/Region,City,State/Province,Postal Code,Region,Product ID,Category,Sub-Category,Sales,Quantity,Discount,Profit
0,1,US-2023-103800,2023-03-01,2023-01-07,Standard Class,DP-13000,Darren Powers,Consumer,United States,Houston,Texas,77095,Central,OFF-PA-10000174,Office Supplies,Paper,53.920,2,0.2,5.5512
1,2,US-2023-112326,2023-01-04,2023-01-08,Standard Class,PO-19195,Phillina Ober,Home Office,United States,Naperville,Illinois,60540,Central,OFF-BI-10004094,Office Supplies,Binders,3.540,2,0.8,6.6846
2,3,US-2023-112326,2023-01-04,2023-01-08,Standard Class,PO-19195,Phillina Ober,Home Office,United States,Naperville,Illinois,60540,Central,OFF-LA-10003223,Office Supplies,Labels,11.784,3,0.2,4.2717
3,4,US-2023-112326,2023-01-04,2023-01-08,Standard Class,PO-19195,Phillina Ober,Home Office,United States,Naperville,Illinois,60540,Central,OFF-ST-10002743,Office Supplies,Storage,53.920,3,0.2,-64.7748
4,5,US-2023-141817,2023-01-05,2023-01-12,Unknown,MB-18085,Mick Brown,Consumer,United States,Philadelphia,Pennsylvania,19143,East,OFF-AR-10003478,Office Supplies,Art,19.536,3,0.2,4.8840
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10698,10190,US-2026-143259,2026-12-30,2027-01-03,Standard Class,PO-18865,Patrick O'Donnell,Consumer,United States,New York City,New York,10009,East,OFF-BI-10003684,Office Supplies,Binders,52.776,3,0.2,19.7910
10699,10191,US-2026-115427,2026-12-30,2027-01-03,Standard Class,EB-13975,Erica Bern,Corporate,United States,Fairfield,California,94533,West,OFF-BI-10004632,Office Supplies,Binders,20.720,2,0.2,6.4750
10700,10192,US-2026-156720,2026-12-30,2027-01-03,Standard Class,JM-15580,Jill Matthias,Consumer,United States,Loveland,Colorado,80538,West,OFF-FA-10003472,Office Supplies,Fasteners,3.024,3,0.2,-0.6048
10701,10193,US-2026-143259,2026-12-30,2027-01-03,Standard Class,PO-18865,Patrick O'Donnell,Consumer,United States,New York City,New York,10009,East,TEC-PH-10004774,Technology,Phones,90.930,7,0.0,2.7279
10702,10194,CA-2026-143500,2026-12-30,2027-01-03,Standard Class,HO-15230,Harry Olson,Consumer,Canada,Charlottetown,Prince Edward Island,C0A,East,OFF-BI-10004040,Office Supplies,Binders,3.024,3,0.2,-0.6048

In [215]:
df[['Sales','Discount','Profit']] = df[['Sales','Discount','Profit']].round().astype(int)
df

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country/Region,City,State/Province,Postal Code,Region,Product ID,Category,Sub-Category,Sales,Quantity,Discount,Profit
0,1,US-2023-103800,2023-03-01,2023-01-07,Standard Class,DP-13000,Darren Powers,Consumer,United States,Houston,Texas,77095,Central,OFF-PA-10000174,Office Supplies,Paper,54,2,0,6
1,2,US-2023-112326,2023-01-04,2023-01-08,Standard Class,PO-19195,Phillina Ober,Home Office,United States,Naperville,Illinois,60540,Central,OFF-BI-10004094,Office Supplies,Binders,4,2,1,7
2,3,US-2023-112326,2023-01-04,2023-01-08,Standard Class,PO-19195,Phillina Ober,Home Office,United States,Naperville,Illinois,60540,Central,OFF-LA-10003223,Office Supplies,Labels,12,3,0,4
3,4,US-2023-112326,2023-01-04,2023-01-08,Standard Class,PO-19195,Phillina Ober,Home Office,United States,Naperville,Illinois,60540,Central,OFF-ST-10002743,Office Supplies,Storage,54,3,0,-65
4,5,US-2023-141817,2023-01-05,2023-01-12,Unknown,MB-18085,Mick Brown,Consumer,United States,Philadelphia,Pennsylvania,19143,East,OFF-AR-10003478,Office Supplies,Art,20,3,0,5
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10698,10190,US-2026-143259,2026-12-30,2027-01-03,Standard Class,PO-18865,Patrick O'Donnell,Consumer,United States,New York City,New York,10009,East,OFF-BI-10003684,Office Supplies,Binders,53,3,0,20
10699,10191,US-2026-115427,2026-12-30,2027-01-03,Standard Class,EB-13975,Erica Bern,Corporate,United States,Fairfield,California,94533,West,OFF-BI-10004632,Office Supplies,Binders,21,2,0,6
10700,10192,US-2026-156720,2026-12-30,2027-01-03,Standard Class,JM-15580,Jill Matthias,Consumer,United States,Loveland,Colorado,80538,West,OFF-FA-10003472,Office Supplies,Fasteners,3,3,0,-1
10701,10193,US-2026-143259,2026-12-30,2027-01-03,Standard Class,PO-18865,Patrick O'Donnell,Consumer,United States,New York City,New York,10009,East,TEC-PH-10004774,Technology,Phones,91,7,0,3
10702,10194,CA-2026-143500,2026-12-30,2027-01-03,Standard Class,HO-15230,Harry Olson,Consumer,Canada,Charlottetown,Prince Edward Island,C0A,East,OFF-BI-10004040,Office Supplies,Binders,3,3,0,-1

In [216]:
df.to_csv('CLEAN_Superstore_Sales.csv', index=False)