In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import os

In [2]:
directory = '../Datasets'

dfs = []

for file in os.listdir(directory):
    if file.endswith('.csv'):
        file_path = os.path.join(directory, file)
        category = file.split('-')[-2]

        df = pd.read_csv(file_path)
        df['category'] = category
        dfs.append(df)

combined_df = pd.concat(dfs, ignore_index=True)

combined_df

,goods-title-link--jump,goods-title-link--jump href,rank-title,rank-sub,price,discount,selling_proposition,goods-title-link,category,color-count,blackfridaybelts-bg src,blackfridaybelts-content,product-locatelabels-img src
0,1pc Rechargeable Deep Tissue Muscle Handheld M...,https://us.shein.com/1pc-Rechargeable-Deep-Tis...,#1 Best Sellers,in Give Gifts,$2.03,-22%,NaN,NaN,appliances,NaN,NaN,NaN,NaN
1,1pc Portable Hanging Neck Fan,https://us.shein.com/1pc-Portable-Hanging-Neck...,#4 Best Sellers,in Top rated in Portable Fans,$6.48,-20%,NaN,NaN,appliances,NaN,NaN,NaN,NaN
2,1pc Pink Colored Curved Eyelash Curler False E...,https://us.shein.com/1pc-Pink-Colored-Curved-E...,NaN,NaN,$1.80,NaN,400+ sold recently,NaN,appliances,NaN,NaN,NaN,NaN
3,1 Mini Portable Handheld Fan With 2 Aa Batteri...,https://us.shein.com/1-Mini-Portable-Handheld-...,NaN,NaN,$0.88,-72%,5.6k+ sold recently,NaN,appliances,NaN,NaN,NaN,NaN
4,"Wit Water Flosser,Portable Oral Irrigator With...",https://us.shein.com/Wit-Water-Flosser-Portabl...,#6 Best Sellers,in Oral Irrigators,$12.06,-40%,NaN,NaN,appliances,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...
82100,NaN,NaN,#2 Best Seller,In Modest World Apparel,$35.69,NaN,NaN,Colorful Flower Embroidered Linen Muslim Women...,womens_clothing,NaN,NaN,NaN,NaN
82101,NaN,NaN,NaN,NaN,$42.49,NaN,10+ sold recently,Elegant And Stylish Patchwork Lace Cheongsam D...,womens_clothing,NaN,NaN,NaN,NaN
82102,NaN,NaN,NaN,NaN,$49.29,NaN,200+ sold recently,Split Thigh Satin Tube Prom Dress,womens_clothing,5.0,NaN,NaN,NaN
82103,NaN,NaN,#10 Best Seller,In Sexy Women Bottoms,$9.78,-5%,NaN,DAZY Women's Solid Color Low Waist Ultra Short...,womens_clothing,6.0,NaN,NaN,NaN
82104,NaN,NaN,NaN,NaN,$21.19,NaN,NaN,SHEIN Najma Women's Elegant Solid Color Batwin...,womens_clothing,NaN,NaN,NaN,https://img.ltwebstatic.com/images3_pi/2022/11...

In [3]:
combined_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 82105 entries, 0 to 82104
Data columns (total 13 columns):
 #   Column                        Non-Null Count  Dtype
---  ------                        --------------  -----
 0   goods-title-link--jump        664 non-null    object
 1   goods-title-link--jump href   664 non-null    object
 2   rank-title                    14605 non-null  object
 3   rank-sub                      14605 non-null  object
 4   price                         82103 non-null  object
 5   discount                      54977 non-null  object
 6   selling_proposition           54364 non-null  object
 7   goods-title-link              81427 non-null  object
 8   category                      82105 non-null  object
 9   color-count                   19743 non-null  float64
 10  blackfridaybelts-bg src       3791 non-null   object
 11  blackfridaybelts-content      3791 non-null   object
 12  product-locatelabels-img src  3622 non-null   object
dtypes: float64(1), object(12)
memory usage: 8.1+ MB

In [4]:
missing_data = (combined_df.isnull().sum() / len(combined_df)) * 100
print(f'Percentage of missing data per column: \n{missing_data}')

Percentage of missing data per column:
goods-title-link--jump          99.191279
goods-title-link--jump href     99.191279
rank-title                      82.211802
rank-sub                        82.211802
price                            0.002436
discount                        33.040619
selling_proposition             33.787224
goods-title-link                 0.825772
category                         0.000000
color-count                     75.953961
blackfridaybelts-bg src         95.382742
blackfridaybelts-content        95.382742
product-locatelabels-img src    95.588576
dtype: float64

In [5]:
df.duplicated().sum()

np.int64(358)

In [6]:
df = combined_df.copy()

In [7]:
df = df.drop_duplicates()

In [8]:
df.duplicated().sum()

np.int64(0)

In [9]:
df['goods-title'] = df['goods-title-link--jump'].fillna('') + df['goods-title-link'].fillna('')
df

,goods-title-link--jump,goods-title-link--jump href,rank-title,rank-sub,price,discount,selling_proposition,goods-title-link,category,color-count,blackfridaybelts-bg src,blackfridaybelts-content,product-locatelabels-img src,goods-title
0,1pc Rechargeable Deep Tissue Muscle Handheld M...,https://us.shein.com/1pc-Rechargeable-Deep-Tis...,#1 Best Sellers,in Give Gifts,$2.03,-22%,NaN,NaN,appliances,NaN,NaN,NaN,NaN,1pc Rechargeable Deep Tissue Muscle Handheld M...
1,1pc Portable Hanging Neck Fan,https://us.shein.com/1pc-Portable-Hanging-Neck...,#4 Best Sellers,in Top rated in Portable Fans,$6.48,-20%,NaN,NaN,appliances,NaN,NaN,NaN,NaN,1pc Portable Hanging Neck Fan
2,1pc Pink Colored Curved Eyelash Curler False E...,https://us.shein.com/1pc-Pink-Colored-Curved-E...,NaN,NaN,$1.80,NaN,400+ sold recently,NaN,appliances,NaN,NaN,NaN,NaN,1pc Pink Colored Curved Eyelash Curler False E...
3,1 Mini Portable Handheld Fan With 2 Aa Batteri...,https://us.shein.com/1-Mini-Portable-Handheld-...,NaN,NaN,$0.88,-72%,5.6k+ sold recently,NaN,appliances,NaN,NaN,NaN,NaN,1 Mini Portable Handheld Fan With 2 Aa Batteri...
4,"Wit Water Flosser,Portable Oral Irrigator With...",https://us.shein.com/Wit-Water-Flosser-Portabl...,#6 Best Sellers,in Oral Irrigators,$12.06,-40%,NaN,NaN,appliances,NaN,NaN,NaN,NaN,"Wit Water Flosser,Portable Oral Irrigator With..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
82100,NaN,NaN,#2 Best Seller,In Modest World Apparel,$35.69,NaN,NaN,Colorful Flower Embroidered Linen Muslim Women...,womens_clothing,NaN,NaN,NaN,NaN,Colorful Flower Embroidered Linen Muslim Women...
82101,NaN,NaN,NaN,NaN,$42.49,NaN,10+ sold recently,Elegant And Stylish Patchwork Lace Cheongsam D...,womens_clothing,NaN,NaN,NaN,NaN,Elegant And Stylish Patchwork Lace Cheongsam D...
82102,NaN,NaN,NaN,NaN,$49.29,NaN,200+ sold recently,Split Thigh Satin Tube Prom Dress,womens_clothing,5.0,NaN,NaN,NaN,Split Thigh Satin Tube Prom Dress
82103,NaN,NaN,#10 Best Seller,In Sexy Women Bottoms,$9.78,-5%,NaN,DAZY Women's Solid Color Low Waist Ultra Short...,womens_clothing,6.0,NaN,NaN,NaN,DAZY Women's Solid Color Low Waist Ultra Short...
82104,NaN,NaN,NaN,NaN,$21.19,NaN,NaN,SHEIN Najma Women's Elegant Solid Color Batwin...,womens_clothing,NaN,NaN,NaN,https://img.ltwebstatic.com/images3_pi/2022/11...,SHEIN Najma Women's Elegant Solid Color Batwin...

In [10]:
df['goods-title'].isnull().sum()

np.int64(0)

In [11]:
df = df.drop(['goods-title-link--jump', 'goods-title-link'], axis=1)
df

,goods-title-link--jump href,rank-title,rank-sub,price,discount,selling_proposition,category,color-count,blackfridaybelts-bg src,blackfridaybelts-content,product-locatelabels-img src,goods-title
0,https://us.shein.com/1pc-Rechargeable-Deep-Tis...,#1 Best Sellers,in Give Gifts,$2.03,-22%,NaN,appliances,NaN,NaN,NaN,NaN,1pc Rechargeable Deep Tissue Muscle Handheld M...
1,https://us.shein.com/1pc-Portable-Hanging-Neck...,#4 Best Sellers,in Top rated in Portable Fans,$6.48,-20%,NaN,appliances,NaN,NaN,NaN,NaN,1pc Portable Hanging Neck Fan
2,https://us.shein.com/1pc-Pink-Colored-Curved-E...,NaN,NaN,$1.80,NaN,400+ sold recently,appliances,NaN,NaN,NaN,NaN,1pc Pink Colored Curved Eyelash Curler False E...
3,https://us.shein.com/1-Mini-Portable-Handheld-...,NaN,NaN,$0.88,-72%,5.6k+ sold recently,appliances,NaN,NaN,NaN,NaN,1 Mini Portable Handheld Fan With 2 Aa Batteri...
4,https://us.shein.com/Wit-Water-Flosser-Portabl...,#6 Best Sellers,in Oral Irrigators,$12.06,-40%,NaN,appliances,NaN,NaN,NaN,NaN,"Wit Water Flosser,Portable Oral Irrigator With..."
...,...,...,...,...,...,...,...,...,...,...,...,...
82100,NaN,#2 Best Seller,In Modest World Apparel,$35.69,NaN,NaN,womens_clothing,NaN,NaN,NaN,NaN,Colorful Flower Embroidered Linen Muslim Women...
82101,NaN,NaN,NaN,$42.49,NaN,10+ sold recently,womens_clothing,NaN,NaN,NaN,NaN,Elegant And Stylish Patchwork Lace Cheongsam D...
82102,NaN,NaN,NaN,$49.29,NaN,200+ sold recently,womens_clothing,5.0,NaN,NaN,NaN,Split Thigh Satin Tube Prom Dress
82103,NaN,#10 Best Seller,In Sexy Women Bottoms,$9.78,-5%,NaN,womens_clothing,6.0,NaN,NaN,NaN,DAZY Women's Solid Color Low Waist Ultra Short...
82104,NaN,NaN,NaN,$21.19,NaN,NaN,womens_clothing,NaN,NaN,NaN,https://img.ltwebstatic.com/images3_pi/2022/11...,SHEIN Najma Women's Elegant Solid Color Batwin...

In [12]:
df = df.drop(['goods-title-link--jump href', 'product-locatelabels-img src', 'blackfridaybelts-bg src', 'blackfridaybelts-content'], axis=1)
df

,rank-title,rank-sub,price,discount,selling_proposition,category,color-count,goods-title
0,#1 Best Sellers,in Give Gifts,$2.03,-22%,NaN,appliances,NaN,1pc Rechargeable Deep Tissue Muscle Handheld M...
1,#4 Best Sellers,in Top rated in Portable Fans,$6.48,-20%,NaN,appliances,NaN,1pc Portable Hanging Neck Fan
2,NaN,NaN,$1.80,NaN,400+ sold recently,appliances,NaN,1pc Pink Colored Curved Eyelash Curler False E...
3,NaN,NaN,$0.88,-72%,5.6k+ sold recently,appliances,NaN,1 Mini Portable Handheld Fan With 2 Aa Batteri...
4,#6 Best Sellers,in Oral Irrigators,$12.06,-40%,NaN,appliances,NaN,"Wit Water Flosser,Portable Oral Irrigator With..."
...,...,...,...,...,...,...,...,...
82100,#2 Best Seller,In Modest World Apparel,$35.69,NaN,NaN,womens_clothing,NaN,Colorful Flower Embroidered Linen Muslim Women...
82101,NaN,NaN,$42.49,NaN,10+ sold recently,womens_clothing,NaN,Elegant And Stylish Patchwork Lace Cheongsam D...
82102,NaN,NaN,$49.29,NaN,200+ sold recently,womens_clothing,5.0,Split Thigh Satin Tube Prom Dress
82103,#10 Best Seller,In Sexy Women Bottoms,$9.78,-5%,NaN,womens_clothing,6.0,DAZY Women's Solid Color Low Waist Ultra Short...
82104,NaN,NaN,$21.19,NaN,NaN,womens_clothing,NaN,SHEIN Najma Women's Elegant Solid Color Batwin...

In [13]:
df.isnull().sum()

rank-title             64951
rank-sub               64951
price                      2
discount               26234
selling_proposition    26720
category                   0
color-count            60306
goods-title                0
dtype: int64

In [14]:
df['price'] = df['price'].replace('[\$,]' , '', regex=True).astype(float)
df

,rank-title,rank-sub,price,discount,selling_proposition,category,color-count,goods-title
0,#1 Best Sellers,in Give Gifts,2.03,-22%,NaN,appliances,NaN,1pc Rechargeable Deep Tissue Muscle Handheld M...
1,#4 Best Sellers,in Top rated in Portable Fans,6.48,-20%,NaN,appliances,NaN,1pc Portable Hanging Neck Fan
2,NaN,NaN,1.80,NaN,400+ sold recently,appliances,NaN,1pc Pink Colored Curved Eyelash Curler False E...
3,NaN,NaN,0.88,-72%,5.6k+ sold recently,appliances,NaN,1 Mini Portable Handheld Fan With 2 Aa Batteri...
4,#6 Best Sellers,in Oral Irrigators,12.06,-40%,NaN,appliances,NaN,"Wit Water Flosser,Portable Oral Irrigator With..."
...,...,...,...,...,...,...,...,...
82100,#2 Best Seller,In Modest World Apparel,35.69,NaN,NaN,womens_clothing,NaN,Colorful Flower Embroidered Linen Muslim Women...
82101,NaN,NaN,42.49,NaN,10+ sold recently,womens_clothing,NaN,Elegant And Stylish Patchwork Lace Cheongsam D...
82102,NaN,NaN,49.29,NaN,200+ sold recently,womens_clothing,5.0,Split Thigh Satin Tube Prom Dress
82103,#10 Best Seller,In Sexy Women Bottoms,9.78,-5%,NaN,womens_clothing,6.0,DAZY Women's Solid Color Low Waist Ultra Short...
82104,NaN,NaN,21.19,NaN,NaN,womens_clothing,NaN,SHEIN Najma Women's Elegant Solid Color Batwin...

In [15]:
category_mean_price = df.groupby('category')['price'].median()

df['price'] = df['price'].fillna(df['category'].map(category_mean_price))

df['discount'] = df['discount'].replace('[%]', '', regex=True).fillna(0).astype(int)

In [16]:
df.isnull().sum()

rank-title             64951
rank-sub               64951
price                      0
discount                   0
selling_proposition    26720
category                   0
color-count            60306
goods-title                0
dtype: int64

In [17]:
def transform_sp(selling_prop):
    if pd.isna(selling_prop):
        return 0
    
    selling_prop = str(selling_prop).lower().replace('+', '').replace(' sold recently', '')

    return int(float(selling_prop.replace('k', '')) * 1000) if 'k' in selling_prop else int(selling_prop)

df['selling_proposition'] = df['selling_proposition'].apply(transform_sp)

In [18]:
df

,rank-title,rank-sub,price,discount,selling_proposition,category,color-count,goods-title
0,#1 Best Sellers,in Give Gifts,2.03,-22,0,appliances,NaN,1pc Rechargeable Deep Tissue Muscle Handheld M...
1,#4 Best Sellers,in Top rated in Portable Fans,6.48,-20,0,appliances,NaN,1pc Portable Hanging Neck Fan
2,NaN,NaN,1.80,0,400,appliances,NaN,1pc Pink Colored Curved Eyelash Curler False E...
3,NaN,NaN,0.88,-72,5600,appliances,NaN,1 Mini Portable Handheld Fan With 2 Aa Batteri...
4,#6 Best Sellers,in Oral Irrigators,12.06,-40,0,appliances,NaN,"Wit Water Flosser,Portable Oral Irrigator With..."
...,...,...,...,...,...,...,...,...
82100,#2 Best Seller,In Modest World Apparel,35.69,0,0,womens_clothing,NaN,Colorful Flower Embroidered Linen Muslim Women...
82101,NaN,NaN,42.49,0,10,womens_clothing,NaN,Elegant And Stylish Patchwork Lace Cheongsam D...
82102,NaN,NaN,49.29,0,200,womens_clothing,5.0,Split Thigh Satin Tube Prom Dress
82103,#10 Best Seller,In Sexy Women Bottoms,9.78,-5,0,womens_clothing,6.0,DAZY Women's Solid Color Low Waist Ultra Short...
82104,NaN,NaN,21.19,0,0,womens_clothing,NaN,SHEIN Najma Women's Elegant Solid Color Batwin...

In [19]:
df['color-count'] = df['color-count'].fillna(0).astype(int)
df

,rank-title,rank-sub,price,discount,selling_proposition,category,color-count,goods-title
0,#1 Best Sellers,in Give Gifts,2.03,-22,0,appliances,0,1pc Rechargeable Deep Tissue Muscle Handheld M...
1,#4 Best Sellers,in Top rated in Portable Fans,6.48,-20,0,appliances,0,1pc Portable Hanging Neck Fan
2,NaN,NaN,1.80,0,400,appliances,0,1pc Pink Colored Curved Eyelash Curler False E...
3,NaN,NaN,0.88,-72,5600,appliances,0,1 Mini Portable Handheld Fan With 2 Aa Batteri...
4,#6 Best Sellers,in Oral Irrigators,12.06,-40,0,appliances,0,"Wit Water Flosser,Portable Oral Irrigator With..."
...,...,...,...,...,...,...,...,...
82100,#2 Best Seller,In Modest World Apparel,35.69,0,0,womens_clothing,0,Colorful Flower Embroidered Linen Muslim Women...
82101,NaN,NaN,42.49,0,10,womens_clothing,0,Elegant And Stylish Patchwork Lace Cheongsam D...
82102,NaN,NaN,49.29,0,200,womens_clothing,5,Split Thigh Satin Tube Prom Dress
82103,#10 Best Seller,In Sexy Women Bottoms,9.78,-5,0,womens_clothing,6,DAZY Women's Solid Color Low Waist Ultra Short...
82104,NaN,NaN,21.19,0,0,womens_clothing,0,SHEIN Najma Women's Elegant Solid Color Batwin...

In [20]:
df['rank-title'] = df['rank-title'].replace('#' , '', regex=True).replace(r' Best Seller[s]?','',regex=True).fillna(0).astype(int)

df = df.drop(['rank-sub'], axis=1)
df

,rank-title,price,discount,selling_proposition,category,color-count,goods-title
0,1,2.03,-22,0,appliances,0,1pc Rechargeable Deep Tissue Muscle Handheld M...
1,4,6.48,-20,0,appliances,0,1pc Portable Hanging Neck Fan
2,0,1.80,0,400,appliances,0,1pc Pink Colored Curved Eyelash Curler False E...
3,0,0.88,-72,5600,appliances,0,1 Mini Portable Handheld Fan With 2 Aa Batteri...
4,6,12.06,-40,0,appliances,0,"Wit Water Flosser,Portable Oral Irrigator With..."
...,...,...,...,...,...,...,...
82100,2,35.69,0,0,womens_clothing,0,Colorful Flower Embroidered Linen Muslim Women...
82101,0,42.49,0,10,womens_clothing,0,Elegant And Stylish Patchwork Lace Cheongsam D...
82102,0,49.29,0,200,womens_clothing,5,Split Thigh Satin Tube Prom Dress
82103,10,9.78,-5,0,womens_clothing,6,DAZY Women's Solid Color Low Waist Ultra Short...
82104,0,21.19,0,0,womens_clothing,0,SHEIN Najma Women's Elegant Solid Color Batwin...

In [21]:
missing_data = (df.isnull().sum() / len(df)) * 100
print(f'Percentage of missing data per column: \n{missing_data}')

Percentage of missing data per column:
rank-title             0.0
price                  0.0
discount               0.0
selling_proposition    0.0
category               0.0
color-count            0.0
goods-title            0.0
dtype: float64

In [22]:
df.to_csv('CLEAN_ecommerce_data.csv', index=False)