In [34]:
import pandas as pd
import numpy as np

In [35]:
df = pd.read_csv('data.csv')
df

  campaign_id  start_date ad_spend impressions     status
0        C101    2026/9/1    2,500       10000  Completed
1        C102  01/09/2026     3200      15,000     active
2        C103    2026/9/5  unknown        8000     ACTIVE
3        C104     invalid     1800        -500    planned
4        C105   2026/9/10     2100        9000    Planned
5        C105   2026/9/10     2100        9000    Planned

In [36]:
df.drop_duplicates(inplace=True)
df

  campaign_id  start_date ad_spend impressions     status
0        C101    2026/9/1    2,500       10000  Completed
1        C102  01/09/2026     3200      15,000     active
2        C103    2026/9/5  unknown        8000     ACTIVE
3        C104     invalid     1800        -500    planned
4        C105   2026/9/10     2100        9000    Planned

In [37]:
df['start_date'] = df['start_date'].replace('invalid',None).pipe(pd.to_datetime,format='mixed')
df

  campaign_id start_date ad_spend impressions     status
0        C101 2026-09-01    2,500       10000  Completed
1        C102 2026-01-09     3200      15,000     active
2        C103 2026-09-05  unknown        8000     ACTIVE
3        C104        NaT     1800        -500    planned
4        C105 2026-09-10     2100        9000    Planned

In [38]:
df['ad_spend'] = df['ad_spend'].replace({',':'','unknown':None}, regex=True).pipe(pd.to_numeric, errors = 'coerce')
df

  campaign_id start_date  ad_spend impressions     status
0        C101 2026-09-01    2500.0       10000  Completed
1        C102 2026-01-09    3200.0      15,000     active
2        C103 2026-09-05       NaN        8000     ACTIVE
3        C104        NaT    1800.0        -500    planned
4        C105 2026-09-10    2100.0        9000    Planned

In [39]:
df['impressions'] = df['impressions'].replace({",":"","-":""}, regex=True).pipe(pd.to_numeric, errors='coerce')
df

  campaign_id start_date  ad_spend  impressions     status
0        C101 2026-09-01    2500.0        10000  Completed
1        C102 2026-01-09    3200.0        15000     active
2        C103 2026-09-05       NaN         8000     ACTIVE
3        C104        NaT    1800.0          500    planned
4        C105 2026-09-10    2100.0         9000    Planned

In [40]:
df['status'] = df['status'].str.strip().str.capitalize()
df

  campaign_id start_date  ad_spend  impressions     status
0        C101 2026-09-01    2500.0        10000  Completed
1        C102 2026-01-09    3200.0        15000     Active
2        C103 2026-09-05       NaN         8000     Active
3        C104        NaT    1800.0          500    Planned
4        C105 2026-09-10    2100.0         9000    Planned