In [59]:
import pandas as pd
import numpy as np

In [60]:
df = pd.read_csv('data.csv')
df

  campaign_id  start_date ad_spend impressions     status
0        C101    2026/9/1    2,500       10000  Completed
1        C102  01/09/2026     3200      15,000     active
2        C103    2026/9/5  unknown        8000     ACTIVE
3        C104     invalid     1800        -500    planned
4        C105   2026/9/10     2100        9000    Planned
5        C105   2026/9/10     2100        9000    Planned

In [61]:
df.drop_duplicates(inplace=True)
df

  campaign_id  start_date ad_spend impressions     status
0        C101    2026/9/1    2,500       10000  Completed
1        C102  01/09/2026     3200      15,000     active
2        C103    2026/9/5  unknown        8000     ACTIVE
3        C104     invalid     1800        -500    planned
4        C105   2026/9/10     2100        9000    Planned

In [62]:
df['start_date'] = df['start_date'].replace('invalid',None).pipe(pd.to_datetime,format='mixed')
df

  campaign_id start_date ad_spend impressions     status
0        C101 2026-09-01    2,500       10000  Completed
1        C102 2026-01-09     3200      15,000     active
2        C103 2026-09-05  unknown        8000     ACTIVE
3        C104        NaT     1800        -500    planned
4        C105 2026-09-10     2100        9000    Planned

In [63]:
df['ad_spend'] = df['ad_spend'].replace({',':'','unknown':None}, regex=True).pipe(pd.to_numeric, errors = 'coerce')
df

  campaign_id start_date  ad_spend impressions     status
0        C101 2026-09-01    2500.0       10000  Completed
1        C102 2026-01-09    3200.0      15,000     active
2        C103 2026-09-05       NaN        8000     ACTIVE
3        C104        NaT    1800.0        -500    planned
4        C105 2026-09-10    2100.0        9000    Planned

In [64]:
df['impressions'] = df['impressions'].replace({",":"","-":""}, regex=True).pipe(pd.to_numeric, errors='coerce')
df

  campaign_id start_date  ad_spend  impressions     status
0        C101 2026-09-01    2500.0        10000  Completed
1        C102 2026-01-09    3200.0        15000     active
2        C103 2026-09-05       NaN         8000     ACTIVE
3        C104        NaT    1800.0          500    planned
4        C105 2026-09-10    2100.0         9000    Planned

In [65]:
df['status'] = df['status'].str.strip().str.capitalize()
df

  campaign_id start_date  ad_spend  impressions     status
0        C101 2026-09-01    2500.0        10000  Completed
1        C102 2026-01-09    3200.0        15000     Active
2        C103 2026-09-05       NaN         8000     Active
3        C104        NaT    1800.0          500    Planned
4        C105 2026-09-10    2100.0         9000    Planned

In [66]:
df["data_issue"] = df[
    ["start_date", "ad_spend", "impressions"]
].isna().any(axis=1)

In [67]:
df

  campaign_id start_date  ad_spend  impressions     status  data_issue
0        C101 2026-09-01    2500.0        10000  Completed       False
1        C102 2026-01-09    3200.0        15000     Active       False
2        C103 2026-09-05       NaN         8000     Active        True
3        C104        NaT    1800.0          500    Planned        True
4        C105 2026-09-10    2100.0         9000    Planned       False

In [68]:
df2 = pd.read_csv('data2.csv')
df3 = pd.read_csv('data3.csv')

In [69]:
all_df = pd.merge(pd.merge(df,df2,on='campaign_id',how="outer"),df3, on='campaign_id',how="outer")
all_df

,campaign_id,start_date,ad_spend,impressions,status,data_issue,campaign_name,channel,lead_id,converted,revenue
0,C101,2026-09-01,2500.0,10000,Completed,False,Autumn Sale,Email,L001,True,8000.0
1,C101,2026-09-01,2500.0,10000,Completed,False,Autumn Sale,Email,L002,False,0.0
2,C101,2026-09-01,2500.0,10000,Completed,False,Autumn Sale,Email,L003,True,5000.0
3,C102,2026-01-09,3200.0,15000,Active,False,New Customer,Social,L004,False,0.0
4,C102,2026-01-09,3200.0,15000,Active,False,New Customer,Social,L005,True,6000.0
5,C103,2026-09-05,NaN,8000,Active,True,Loyalty Bonus,Email,L006,False,0.0
6,C104,NaT,1800.0,500,Planned,True,Search Promo,Search,NaN,NaN,NaN
7,C105,2026-09-10,2100.0,9000,Planned,False,NaN,NaN,NaN,NaN,NaN

In [70]:
all_df.to_csv('total_data.csv')