In [39]:
import pandas as pd

In [40]:
df = pd.read_csv('data.csv')
df

   order_id distance_km  item_count peak_hour   weather delivery_minutes
0      O101         3.2           2        No     Clear               32
1      O102         5.5           4       yes      Rain               48
2      O103           2           1        NO     clear               25
3      O104         6.1           3       Yes      RAIN               42
4      O105           4           2        no    Cloudy               38
5      O106       eight           5       Yes      Rain               61
6      O107        -1.5           2        No     Clear               29
7      O108         3.8          -2       yes   cloudy                40
8      O109         7.2           4       Yes     Clear               55
9      O110         1.5           1        No     Clear               20
10     O111           5           3       Yes   unknown          unknown
11     O111           5           3       Yes   unknown          unknown

duplicates are removed

In [41]:
df.drop_duplicates(inplace=True)
df

   order_id distance_km  item_count peak_hour   weather delivery_minutes
0      O101         3.2           2        No     Clear               32
1      O102         5.5           4       yes      Rain               48
2      O103           2           1        NO     clear               25
3      O104         6.1           3       Yes      RAIN               42
4      O105           4           2        no    Cloudy               38
5      O106       eight           5       Yes      Rain               61
6      O107        -1.5           2        No     Clear               29
7      O108         3.8          -2       yes   cloudy                40
8      O109         7.2           4       Yes     Clear               55
9      O110         1.5           1        No     Clear               20
10     O111           5           3       Yes   unknown          unknown

"eight" becomes 8

In [42]:
df["distance_km"] = df["distance_km"].replace("eight",8).pipe(pd.to_numeric, errors="coerce")
df

   order_id  distance_km  item_count peak_hour   weather delivery_minutes
0      O101          3.2           2        No     Clear               32
1      O102          5.5           4       yes      Rain               48
2      O103          2.0           1        NO     clear               25
3      O104          6.1           3       Yes      RAIN               42
4      O105          4.0           2        no    Cloudy               38
5      O106          8.0           5       Yes      Rain               61
6      O107         -1.5           2        No     Clear               29
7      O108          3.8          -2       yes   cloudy                40
8      O109          7.2           4       Yes     Clear               55
9      O110          1.5           1        No     Clear               20
10     O111          5.0           3       Yes   unknown          unknown

numeric columns are converted correctly

In [43]:
numeric_columns = [
    "distance_km",
    "item_count",
    "delivery_minutes"
]

for column in numeric_columns:
    df[column] = pd.to_numeric(
        df[column],
        errors="coerce"
    )

negative distance and item counts become missing

In [44]:
df[["distance_km","item_count"]] = df[["distance_km","item_count"]].mask(df[["distance_km","item_count"]] < 0)
df

   order_id  distance_km  item_count peak_hour   weather  delivery_minutes
0      O101          3.2         2.0        No     Clear              32.0
1      O102          5.5         4.0       yes      Rain              48.0
2      O103          2.0         1.0        NO     clear              25.0
3      O104          6.1         3.0       Yes      RAIN              42.0
4      O105          4.0         2.0        no    Cloudy              38.0
5      O106          8.0         5.0       Yes      Rain              61.0
6      O107          NaN         2.0        No     Clear              29.0
7      O108          3.8         NaN       yes   cloudy               40.0
8      O109          7.2         4.0       Yes     Clear              55.0
9      O110          1.5         1.0        No     Clear              20.0
10     O111          5.0         3.0       Yes   unknown               NaN

peak_hour becomes Boolean

In [45]:
df["peak_hour"] = (df["peak_hour"].str.strip().str.lower().map({"yes":True,"no":False}))
df

   order_id  distance_km  item_count  peak_hour   weather  delivery_minutes
0      O101          3.2         2.0      False     Clear              32.0
1      O102          5.5         4.0       True      Rain              48.0
2      O103          2.0         1.0      False     clear              25.0
3      O104          6.1         3.0       True      RAIN              42.0
4      O105          4.0         2.0      False    Cloudy              38.0
5      O106          8.0         5.0       True      Rain              61.0
6      O107          NaN         2.0      False     Clear              29.0
7      O108          3.8         NaN       True   cloudy               40.0
8      O109          7.2         4.0       True     Clear              55.0
9      O110          1.5         1.0      False     Clear              20.0
10     O111          5.0         3.0       True   unknown               NaN

weather values have consistent capitalization & "unknown" weather becomes Unknown

In [46]:
df["weather"] = df["weather"].str.capitalize()
df

   order_id  distance_km  item_count  peak_hour   weather  delivery_minutes
0      O101          3.2         2.0      False     Clear              32.0
1      O102          5.5         4.0       True      Rain              48.0
2      O103          2.0         1.0      False     Clear              25.0
3      O104          6.1         3.0       True      Rain              42.0
4      O105          4.0         2.0      False    Cloudy              38.0
5      O106          8.0         5.0       True      Rain              61.0
6      O107          NaN         2.0      False     Clear              29.0
7      O108          3.8         NaN       True   cloudy               40.0
8      O109          7.2         4.0       True     Clear              55.0
9      O110          1.5         1.0      False     Clear              20.0
10     O111          5.0         3.0       True   Unknown               NaN

data_issue flags missing distance, item count, or delivery time

In [47]:
required_columns = [
    "distance_km",
    "item_count"
]

df["data_issue"] = df[required_columns].isna().any(axis=1)
df

,order_id,distance_km,item_count,peak_hour,weather,delivery_minutes,data_issue
0,O101,3.2,2.0,False,Clear,32.0,False
1,O102,5.5,4.0,True,Rain,48.0,False
2,O103,2.0,1.0,False,Clear,25.0,False
3,O104,6.1,3.0,True,Rain,42.0,False
4,O105,4.0,2.0,False,Cloudy,38.0,False
5,O106,8.0,5.0,True,Rain,61.0,False
6,O107,NaN,2.0,False,Clear,29.0,True
7,O108,3.8,NaN,True,cloudy,40.0,True
8,O109,7.2,4.0,True,Clear,55.0,False
9,O110,1.5,1.0,False,Clear,20.0,False
10,O111,5.0,3.0,True,Unknown,NaN,False

In [48]:
df =df.fillna(0)
df

,order_id,distance_km,item_count,peak_hour,weather,delivery_minutes,data_issue
0,O101,3.2,2.0,False,Clear,32.0,False
1,O102,5.5,4.0,True,Rain,48.0,False
2,O103,2.0,1.0,False,Clear,25.0,False
3,O104,6.1,3.0,True,Rain,42.0,False
4,O105,4.0,2.0,False,Cloudy,38.0,False
5,O106,8.0,5.0,True,Rain,61.0,False
6,O107,0.0,2.0,False,Clear,29.0,True
7,O108,3.8,0.0,True,cloudy,40.0,True
8,O109,7.2,4.0,True,Clear,55.0,False
9,O110,1.5,1.0,False,Clear,20.0,False
10,O111,5.0,3.0,True,Unknown,0.0,False

In [49]:
df.to_csv("cleaned_data.csv")

In [50]:
df2 = pd.read_csv("data2.csv")
df2

  restaurant_id restaurant_name      area
0          R101  Sakura Kitchen   Shibuya
1          R102      Green Bowl  Shinjuku
2          R103     Tokyo Curry    Meguro
3          R104     Pasta House   Shibuya

In [51]:
df3 = pd.read_csv("data3.csv")
df3

  order_id restaurant_id  delivery_minutes  promised_minutes  revenue
0     O101          R101                32                40     2400
1     O102          R101                48                40     3100
2     O103          R102                25                30     1000
3     O104          R102                42                30     2600
4     O105          R103                38                45     2200

In [52]:
df

,order_id,distance_km,item_count,peak_hour,weather,delivery_minutes,data_issue
0,O101,3.2,2.0,False,Clear,32.0,False
1,O102,5.5,4.0,True,Rain,48.0,False
2,O103,2.0,1.0,False,Clear,25.0,False
3,O104,6.1,3.0,True,Rain,42.0,False
4,O105,4.0,2.0,False,Cloudy,38.0,False
5,O106,8.0,5.0,True,Rain,61.0,False
6,O107,0.0,2.0,False,Clear,29.0,True
7,O108,3.8,0.0,True,cloudy,40.0,True
8,O109,7.2,4.0,True,Clear,55.0,False
9,O110,1.5,1.0,False,Clear,20.0,False
10,O111,5.0,3.0,True,Unknown,0.0,False

In [53]:
df4 = pd.merge(df2,df3, on="restaurant_id", how="inner")
df4

,restaurant_id,restaurant_name,area,order_id,delivery_minutes,promised_minutes,revenue
0,R101,Sakura Kitchen,Shibuya,O101,32,40,2400
1,R101,Sakura Kitchen,Shibuya,O102,48,40,3100
2,R102,Green Bowl,Shinjuku,O103,25,30,1000
3,R102,Green Bowl,Shinjuku,O104,42,30,2600
4,R103,Tokyo Curry,Meguro,O105,38,45,2200

In [54]:
all_df = pd.merge(df,df4.drop(columns="delivery_minutes"), on="order_id",how="right")
all_df

,order_id,distance_km,item_count,peak_hour,weather,delivery_minutes,data_issue,restaurant_id,restaurant_name,area,promised_minutes,revenue
0,O101,3.2,2.0,False,Clear,32.0,False,R101,Sakura Kitchen,Shibuya,40,2400
1,O102,5.5,4.0,True,Rain,48.0,False,R101,Sakura Kitchen,Shibuya,40,3100
2,O103,2.0,1.0,False,Clear,25.0,False,R102,Green Bowl,Shinjuku,30,1000
3,O104,6.1,3.0,True,Rain,42.0,False,R102,Green Bowl,Shinjuku,30,2600
4,O105,4.0,2.0,False,Cloudy,38.0,False,R103,Tokyo Curry,Meguro,45,2200

In [55]:
all_df.to_csv("complete_data.csv")