In [8]:
import pandas as pd

In [9]:
df = pd.read_csv('data.csv')
df

   order_id distance_km  item_count peak_hour   weather delivery_minutes
0      O101         3.2           2        No     Clear               32
1      O102         5.5           4       yes      Rain               48
2      O103           2           1        NO     clear               25
3      O104         6.1           3       Yes      RAIN               42
4      O105           4           2        no    Cloudy               38
5      O106       eight           5       Yes      Rain               61
6      O107        -1.5           2        No     Clear               29
7      O108         3.8          -2       yes   cloudy                40
8      O109         7.2           4       Yes     Clear               55
9      O110         1.5           1        No     Clear               20
10     O111           5           3       Yes   unknown          unknown
11     O111           5           3       Yes   unknown          unknown

duplicates are removed

In [10]:
df.drop_duplicates(inplace=True)
df

   order_id distance_km  item_count peak_hour   weather delivery_minutes
0      O101         3.2           2        No     Clear               32
1      O102         5.5           4       yes      Rain               48
2      O103           2           1        NO     clear               25
3      O104         6.1           3       Yes      RAIN               42
4      O105           4           2        no    Cloudy               38
5      O106       eight           5       Yes      Rain               61
6      O107        -1.5           2        No     Clear               29
7      O108         3.8          -2       yes   cloudy                40
8      O109         7.2           4       Yes     Clear               55
9      O110         1.5           1        No     Clear               20
10     O111           5           3       Yes   unknown          unknown

"eight" becomes 8 and numeric columns are converted correctly

In [11]:
df["distance_km"] = df["distance_km"].replace("eight",8).pipe(pd.to_numeric, errors="coerce")
df

   order_id  distance_km  item_count peak_hour   weather delivery_minutes
0      O101          3.2           2        No     Clear               32
1      O102          5.5           4       yes      Rain               48
2      O103          2.0           1        NO     clear               25
3      O104          6.1           3       Yes      RAIN               42
4      O105          4.0           2        no    Cloudy               38
5      O106          8.0           5       Yes      Rain               61
6      O107         -1.5           2        No     Clear               29
7      O108          3.8          -2       yes   cloudy                40
8      O109          7.2           4       Yes     Clear               55
9      O110          1.5           1        No     Clear               20
10     O111          5.0           3       Yes   unknown          unknown

negative distance and item counts become missing

In [12]:
df[["distance_km","item_count"]] = df[["distance_km","item_count"]].mask(df[["distance_km","item_count"]] < 0)
df

   order_id  distance_km  item_count peak_hour   weather delivery_minutes
0      O101          3.2         2.0        No     Clear               32
1      O102          5.5         4.0       yes      Rain               48
2      O103          2.0         1.0        NO     clear               25
3      O104          6.1         3.0       Yes      RAIN               42
4      O105          4.0         2.0        no    Cloudy               38
5      O106          8.0         5.0       Yes      Rain               61
6      O107          NaN         2.0        No     Clear               29
7      O108          3.8         NaN       yes   cloudy                40
8      O109          7.2         4.0       Yes     Clear               55
9      O110          1.5         1.0        No     Clear               20
10     O111          5.0         3.0       Yes   unknown          unknown

peak_hour becomes Boolean

In [13]:
df["peak_hour"] = (df["peak_hour"].str.strip().str.lower().map({"yes":True,"no":False}))
df

   order_id  distance_km  item_count  peak_hour   weather delivery_minutes
0      O101          3.2         2.0      False     Clear               32
1      O102          5.5         4.0       True      Rain               48
2      O103          2.0         1.0      False     clear               25
3      O104          6.1         3.0       True      RAIN               42
4      O105          4.0         2.0      False    Cloudy               38
5      O106          8.0         5.0       True      Rain               61
6      O107          NaN         2.0      False     Clear               29
7      O108          3.8         NaN       True   cloudy                40
8      O109          7.2         4.0       True     Clear               55
9      O110          1.5         1.0      False     Clear               20
10     O111          5.0         3.0       True   unknown          unknown

weather values have consistent capitalization & "unknown" weather becomes Unknown

In [14]:
df["weather"] = df["weather"].str.capitalize()
df

   order_id  distance_km  item_count  peak_hour   weather delivery_minutes
0      O101          3.2         2.0      False     Clear               32
1      O102          5.5         4.0       True      Rain               48
2      O103          2.0         1.0      False     Clear               25
3      O104          6.1         3.0       True      Rain               42
4      O105          4.0         2.0      False    Cloudy               38
5      O106          8.0         5.0       True      Rain               61
6      O107          NaN         2.0      False     Clear               29
7      O108          3.8         NaN       True   cloudy                40
8      O109          7.2         4.0       True     Clear               55
9      O110          1.5         1.0      False     Clear               20
10     O111          5.0         3.0       True   Unknown          unknown

data_issue flags missing distance, item count, or delivery time

In [15]:
required_columns = [
    "distance_km",
    "item_count"
]

df["data_issue"] = df[required_columns].isna().any(axis=1)
df

,order_id,distance_km,item_count,peak_hour,weather,delivery_minutes,data_issue
0,O101,3.2,2.0,False,Clear,32,False
1,O102,5.5,4.0,True,Rain,48,False
2,O103,2.0,1.0,False,Clear,25,False
3,O104,6.1,3.0,True,Rain,42,False
4,O105,4.0,2.0,False,Cloudy,38,False
5,O106,8.0,5.0,True,Rain,61,False
6,O107,NaN,2.0,False,Clear,29,True
7,O108,3.8,NaN,True,cloudy,40,True
8,O109,7.2,4.0,True,Clear,55,False
9,O110,1.5,1.0,False,Clear,20,False
10,O111,5.0,3.0,True,Unknown,unknown,False

In [16]:
df.to_csv("cleaned_data.csv")