In [40]:
import pandas as pd
import numpy as np

In [41]:
df = pd.read_csv('data.csv')
df

  ticket_id satisfaction_score contact_channel issue_type
0      T101                  5           Email      Login
1      T102                  3          email     Payment
2      T103                NaN            CHAT      login
3      T104                  6           Phone   Delivery
4      T105                two            chat    Payment
5      T105                two            chat    Payment
6      T106                NaN           PHONE    Unknown

In [42]:
df.drop_duplicates(inplace=True)
df

  ticket_id satisfaction_score contact_channel issue_type
0      T101                  5           Email      Login
1      T102                  3          email     Payment
2      T103                NaN            CHAT      login
3      T104                  6           Phone   Delivery
4      T105                two            chat    Payment
6      T106                NaN           PHONE    Unknown

In [43]:
df["satisfaction_score"] = df["satisfaction_score"].replace({"6":None, "two":2}).pipe(pd.to_numeric, errors="coerce")
df

  ticket_id  satisfaction_score contact_channel issue_type
0      T101                 5.0           Email      Login
1      T102                 3.0          email     Payment
2      T103                 NaN            CHAT      login
3      T104                 NaN           Phone   Delivery
4      T105                 2.0            chat    Payment
6      T106                 NaN           PHONE    Unknown

In [44]:
df[["contact_channel","issue_type"]] = df[["contact_channel","issue_type"]].apply(lambda x: x.str.strip().str.capitalize())
df

  ticket_id  satisfaction_score contact_channel issue_type
0      T101                 5.0           Email      Login
1      T102                 3.0           Email    Payment
2      T103                 NaN            Chat      Login
3      T104                 NaN           Phone   Delivery
4      T105                 2.0            Chat    Payment
6      T106                 NaN           Phone    Unknown

In [45]:
df2 = pd.read_csv('data2.csv')
df2

  ticket_id agent_id            opened_at            closed_at priority
0      T101      A01  2026-09-01 09:00:00  2026-09-01 13:00:00     High
1      T102      A02  2026-09-01 10:00:00  2026-09-02 10:00:00   Medium
2      T103      A01  2026-09-02 08:00:00                  NaN     High
3      T104      A03  2026-09-02 11:00:00  2026-09-02 14:00:00      Low
4      T105      A02  2026-09-03 09:00:00  2026-09-03 15:00:00     High
5      T106      A03  2026-09-03 12:00:00                  NaN   Medium

In [46]:
all_df = pd.merge(df,df2, on ="ticket_id", how="inner")
all_df

,ticket_id,satisfaction_score,contact_channel,issue_type,agent_id,opened_at,closed_at,priority
0,T101,5.0,Email,Login,A01,2026-09-01 09:00:00,2026-09-01 13:00:00,High
1,T102,3.0,Email,Payment,A02,2026-09-01 10:00:00,2026-09-02 10:00:00,Medium
2,T103,NaN,Chat,Login,A01,2026-09-02 08:00:00,NaN,High
3,T104,NaN,Phone,Delivery,A03,2026-09-02 11:00:00,2026-09-02 14:00:00,Low
4,T105,2.0,Chat,Payment,A02,2026-09-03 09:00:00,2026-09-03 15:00:00,High
5,T106,NaN,Phone,Unknown,A03,2026-09-03 12:00:00,NaN,Medium

In [47]:
all_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6 entries, 0 to 5
Data columns (total 8 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   ticket_id           6 non-null      object
 1   satisfaction_score  3 non-null      float64
 2   contact_channel     6 non-null      object
 3   issue_type          6 non-null      object
 4   agent_id            6 non-null      object
 5   opened_at           6 non-null      object
 6   closed_at           4 non-null      object
 7   priority            6 non-null      object
dtypes: float64(1), object(7)
memory usage: 516.0+ bytes

In [48]:
all_df[["opened_at","closed_at"]] = all_df[["opened_at","closed_at"]].apply(pd.to_datetime, format="mixed")
all_df

,ticket_id,satisfaction_score,contact_channel,issue_type,agent_id,opened_at,closed_at,priority
0,T101,5.0,Email,Login,A01,2026-09-01 09:00:00,2026-09-01 13:00:00,High
1,T102,3.0,Email,Payment,A02,2026-09-01 10:00:00,2026-09-02 10:00:00,Medium
2,T103,NaN,Chat,Login,A01,2026-09-02 08:00:00,NaT,High
3,T104,NaN,Phone,Delivery,A03,2026-09-02 11:00:00,2026-09-02 14:00:00,Low
4,T105,2.0,Chat,Payment,A02,2026-09-03 09:00:00,2026-09-03 15:00:00,High
5,T106,NaN,Phone,Unknown,A03,2026-09-03 12:00:00,NaT,Medium

In [49]:
all_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6 entries, 0 to 5
Data columns (total 8 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   ticket_id           6 non-null      object
 1   satisfaction_score  3 non-null      float64
 2   contact_channel     6 non-null      object
 3   issue_type          6 non-null      object
 4   agent_id            6 non-null      object
 5   opened_at           6 non-null      datetime64[ns]
 6   closed_at           4 non-null      datetime64[ns]
 7   priority            6 non-null      object
dtypes: datetime64[ns](2), float64(1), object(5)
memory usage: 516.0+ bytes

In [50]:
df = all_df[["ticket_id","agent_id","satisfaction_score","contact_channel","issue_type","opened_at","closed_at","priority"]]
df

,ticket_id,agent_id,satisfaction_score,contact_channel,issue_type,opened_at,closed_at,priority
0,T101,A01,5.0,Email,Login,2026-09-01 09:00:00,2026-09-01 13:00:00,High
1,T102,A02,3.0,Email,Payment,2026-09-01 10:00:00,2026-09-02 10:00:00,Medium
2,T103,A01,NaN,Chat,Login,2026-09-02 08:00:00,NaT,High
3,T104,A03,NaN,Phone,Delivery,2026-09-02 11:00:00,2026-09-02 14:00:00,Low
4,T105,A02,2.0,Chat,Payment,2026-09-03 09:00:00,2026-09-03 15:00:00,High
5,T106,A03,NaN,Phone,Unknown,2026-09-03 12:00:00,NaT,Medium

In [51]:
df.to_csv("complete_data.csv")