In [41]:
import pandas as pd
import numpy as np

In [42]:
df = pd.read_csv('data.csv')
df

  ticket_id satisfaction_score contact_channel issue_type
0      T101                  5           Email      Login
1      T102                  3          email     Payment
2      T103                NaN            CHAT      login
3      T104                  6           Phone   Delivery
4      T105                two            chat    Payment
5      T105                two            chat    Payment
6      T106                NaN           PHONE    Unknown

In [43]:
df.drop_duplicates(inplace=True)
df

  ticket_id satisfaction_score contact_channel issue_type
0      T101                  5           Email      Login
1      T102                  3          email     Payment
2      T103                NaN            CHAT      login
3      T104                  6           Phone   Delivery
4      T105                two            chat    Payment
6      T106                NaN           PHONE    Unknown

In [44]:
df["satisfaction_score"] = df["satisfaction_score"].replace({"6":None, "two":2}).pipe(pd.to_numeric, errors="coerce")
df

  ticket_id  satisfaction_score contact_channel issue_type
0      T101                 5.0           Email      Login
1      T102                 3.0          email     Payment
2      T103                 NaN            CHAT      login
3      T104                 NaN           Phone   Delivery
4      T105                 2.0            chat    Payment
6      T106                 NaN           PHONE    Unknown

In [45]:
df[["contact_channel","issue_type"]] = df[["contact_channel","issue_type"]].apply(lambda x: x.str.strip().str.capitalize())
df

  ticket_id  satisfaction_score contact_channel issue_type
0      T101                 5.0           Email      Login
1      T102                 3.0           Email    Payment
2      T103                 NaN            Chat      Login
3      T104                 NaN           Phone   Delivery
4      T105                 2.0            Chat    Payment
6      T106                 NaN           Phone    Unknown