In [2]:
import pandas as pd

In [3]:
df = pd.read_csv('../Datasets/trx-extra-10k.csv')
df

,id,status,time,card_type,city,amount,fees,discount,balance_before,is_weekend
0,1,processing,2024-12-02 02:58:00,nano,Sanandaj,470243,1511,13581,2569935,0
1,2,pending,2024-02-16 14:02:00,visa,Isfahan,4025070,5336,27780,5584229,0
2,3,processing,2024-06-10 14:23:00,visa,Hamadan,3573895,1686,7350,8785525,1
3,4,pending,2024-02-22 14:03:00,nano,Karaj,4961173,6583,12284,7120096,0
4,5,success,2024-04-04 22:10:00,mastercard,Hamadan,2067746,5001,24609,6591467,1
...,...,...,...,...,...,...,...,...,...,...
9995,9996,success,2024-11-11 11:07:00,debit,Ahvaz,3198034,2382,9864,7053952,1
9996,9997,failed,2024-04-13 07:14:00,nano,Qazvin,2566055,2491,16481,7747502,0
9997,9998,failed,2024-03-17 11:53:00,virtual,Kerman,1374804,2207,12033,1516605,1
9998,9999,processing,2024-05-31 03:35:00,credit,Qazvin,1589514,2222,7967,5362769,0
9999,10000,success,2024-02-25 02:15:00,credit,Yazd,251619,5568,25099,4251064,0

In [4]:
df.isnull().sum()

id                0
status            0
time              0
card_type         0
city              0
amount            0
fees              0
discount          0
balance_before    0
is_weekend        0
dtype: int64

In [5]:
print(df.dtypes)

id                 int64
status            object
time              object
card_type         object
city              object
amount             int64
fees               int64
discount           int64
balance_before     int64
is_weekend         int64
dtype: object

In [6]:
df['time'] = pd.to_datetime(df['time'] , format='mixed')
df

,id,status,time,card_type,city,amount,fees,discount,balance_before,is_weekend
0,1,processing,2024-12-02 02:58:00,nano,Sanandaj,470243,1511,13581,2569935,0
1,2,pending,2024-02-16 14:02:00,visa,Isfahan,4025070,5336,27780,5584229,0
2,3,processing,2024-06-10 14:23:00,visa,Hamadan,3573895,1686,7350,8785525,1
3,4,pending,2024-02-22 14:03:00,nano,Karaj,4961173,6583,12284,7120096,0
4,5,success,2024-04-04 22:10:00,mastercard,Hamadan,2067746,5001,24609,6591467,1
...,...,...,...,...,...,...,...,...,...,...
9995,9996,success,2024-11-11 11:07:00,debit,Ahvaz,3198034,2382,9864,7053952,1
9996,9997,failed,2024-04-13 07:14:00,nano,Qazvin,2566055,2491,16481,7747502,0
9997,9998,failed,2024-03-17 11:53:00,virtual,Kerman,1374804,2207,12033,1516605,1
9998,9999,processing,2024-05-31 03:35:00,credit,Qazvin,1589514,2222,7967,5362769,0
9999,10000,success,2024-02-25 02:15:00,credit,Yazd,251619,5568,25099,4251064,0

In [7]:
print(df.dtypes)

id                         int64
status                    object
time              datetime64[ns]
card_type                 object
city                      object
amount                     int64
fees                       int64
discount                   int64
balance_before             int64
is_weekend                 int64
dtype: object

In [8]:
df['status'].unique()

array(['processing', 'pending', 'success', 'reversed', 'failed'],
      dtype=object)

In [9]:
df['card_type'].unique()

array(['nano', 'visa', 'mastercard', 'prepaid', 'credit', 'debit', 'gift',
       'micro', 'virtual', 'shaparak'], dtype=object)

In [10]:
df['city'].unique()

array(['Sanandaj', 'Isfahan', 'Hamadan', 'Karaj', 'Tehran', 'Urmia',
       'Arak', 'Qazvin', 'Kermanshah', 'Shiraz', 'Tabriz', 'Qom',
       'Kerman', 'Mashhad', 'Rasht', 'Yazd', 'Kashan', 'Bandar Abbas',
       'Ahvaz'], dtype=object)