In [1]:
import pandas as pd
import sqlite3
import matplotlib.pyplot as plt
import seaborn as sns
sns.set()

In [ ]:
# Read in CSV files
brands = pd.read_csv('../Datasets/brands.csv')
categories = pd.read_csv('../Datasets/categories.csv')
customers = pd.read_csv('../Datasets/customers.csv')
order_items = pd.read_csv('../Datasets/order_items.csv')
orders = pd.read_csv('../Datasets/orders.csv')
products = pd.read_csv('../Datasets/products.csv')
staffs = pd.read_csv('../Datasets/staffs.csv')
stocks = pd.read_csv('../Datasets/stocks.csv')
stores = pd.read_csv('../Datasets/stores.csv')

In [3]:
#Create database connection
connection = sqlite3.connect('Bike_Store_Sales_Data.db')

In [4]:
#Insert data into database
brands.to_sql('brands', connection, if_exists='replace', index=False)
categories.to_sql('categories', connection, if_exists='replace', index=False)
customers.to_sql('customers', connection, if_exists='replace', index=False)
order_items.to_sql('order_items', connection, if_exists='replace', index=False)
orders.to_sql('orders', connection, if_exists='replace', index=False)
products.to_sql('products', connection, if_exists='replace', index=False)
staffs.to_sql('staffs', connection, if_exists='replace', index=False)
stocks.to_sql('stocks', connection, if_exists='replace', index=False)
stores.to_sql('stores', connection, if_exists='replace', index=False)

3

SELECT & FROM

In [5]:
# Run SQL query and load results into a DataFrame
query = """
SELECT
    category_name
FROM
    categories;
"""

df = pd.read_sql_query(query, connection)
df

         category_name
0    Children Bicycles
1     Comfort Bicycles
2    Cruisers Bicycles
3  Cyclocross Bicycles
4       Electric Bikes
5       Mountain Bikes
6           Road Bikes

In [6]:
query = """
SELECT
    *
FROM
    categories;
"""

df = pd.read_sql_query(query, connection)
df

   category_id        category_name
0            1    Children Bicycles
1            2     Comfort Bicycles
2            3    Cruisers Bicycles
3            4  Cyclocross Bicycles
4            5       Electric Bikes
5            6       Mountain Bikes
6            7           Road Bikes

ORDER BY,DISTINCT,LIMIT

In [8]:
query = """
SELECT
    first_name,
    last_name
FROM
    customers
ORDER BY
    last_name;
"""

df = pd.read_sql_query(query, connection)
df

      first_name  last_name
0         Jamika    Acevedo
1          Penny    Acevedo
2          Ester    Acevedo
3          Shery     Acosta
4       Bettyann     Acosta
...          ...        ...
1440        Edda      Young
1441      Jasmin      Young
1442       Jayme     Zamora
1443  Alexandria     Zamora
1444       Ollie  Zimmerman

[1445 rows x 2 columns]

In [9]:
query = """
SELECT
    first_name,
    last_name
FROM
    customers
ORDER BY
    last_name, first_name;
"""

df = pd.read_sql_query(query, connection)
df

      first_name  last_name
0          Ester    Acevedo
1         Jamika    Acevedo
2          Penny    Acevedo
3       Bettyann     Acosta
4          Shery     Acosta
...          ...        ...
1440        Edda      Young
1441      Jasmin      Young
1442  Alexandria     Zamora
1443       Jayme     Zamora
1444       Ollie  Zimmerman

[1445 rows x 2 columns]

In [10]:
query = """
SELECT
    DISTINCT
    last_name
FROM
    customers
ORDER BY
    last_name DESC;
"""

df = pd.read_sql_query(query, connection)
df

     last_name
0    Zimmerman
1       Zamora
2        Young
3        Yates
4         Yang
..         ...
748    Aguilar
749     Adkins
750      Adams
751     Acosta
752    Acevedo

[753 rows x 1 columns]

In [11]:
query = """
SELECT
    DISTINCT
    last_name
FROM
    customers
ORDER BY
    last_name ASC
LIMIT 5;
"""

df = pd.read_sql_query(query, connection)
df

  last_name
0   Acevedo
1    Acosta
2     Adams
3    Adkins
4   Aguilar

WHERE, AND. OR