In [159]:
import pandas as pd
import numpy as np

In [160]:
df = pd.read_csv('data.csv')
df

  member_id   join_date     age     status monthly_fee
0      M101   2026/1/15      28     Active       5,000
1      M102  15/02/2026  thirty    active         8000
2      M103   2026/3/10      41     ACTIVE        5000
3      M104     invalid      35  cancelled       8,000
4      M105    2026/5/1      -2     Active        5000
5      M105    2026/5/1      -2     Active        5000

In [161]:
df.info

<bound method DataFrame.info of   member_id   join_date     age     status monthly_fee
0      M101   2026/1/15      28     Active       5,000
1      M102  15/02/2026  thirty    active         8000
2      M103   2026/3/10      41     ACTIVE        5000
3      M104     invalid      35  cancelled       8,000
4      M105    2026/5/1      -2     Active        5000
5      M105    2026/5/1      -2     Active        5000>

In [162]:
df.drop_duplicates(inplace=True)
df

  member_id   join_date     age     status monthly_fee
0      M101   2026/1/15      28     Active       5,000
1      M102  15/02/2026  thirty    active         8000
2      M103   2026/3/10      41     ACTIVE        5000
3      M104     invalid      35  cancelled       8,000
4      M105    2026/5/1      -2     Active        5000

In [163]:
df["join_date"] = df["join_date"].apply(lambda x:None if x=="invalid" else pd.to_datetime(x, format="mixed"))
df

  member_id  join_date     age     status monthly_fee
0      M101 2026-01-15      28     Active       5,000
1      M102 2026-02-15  thirty    active         8000
2      M103 2026-03-10      41     ACTIVE        5000
3      M104        NaT      35  cancelled       8,000
4      M105 2026-05-01      -2     Active        5000

In [164]:
df["status"] = df["status"].str.strip().str.capitalize()
df

  member_id  join_date     age     status monthly_fee
0      M101 2026-01-15      28     Active       5,000
1      M102 2026-02-15  thirty     Active        8000
2      M103 2026-03-10      41     Active        5000
3      M104        NaT      35  Cancelled       8,000
4      M105 2026-05-01      -2     Active        5000

In [165]:
df["age"] = df["age"].replace({"thirty":30, "-2":None}).pipe(pd.to_numeric, errors="coerce")
df

  member_id  join_date   age     status monthly_fee
0      M101 2026-01-15  28.0     Active       5,000
1      M102 2026-02-15  30.0     Active        8000
2      M103 2026-03-10  41.0     Active        5000
3      M104        NaT  35.0  Cancelled       8,000
4      M105 2026-05-01   NaN     Active        5000

In [166]:
df["monthly_fee"] = df["monthly_fee"].str.replace(",","").pipe(pd.to_numeric, errors="coerce")
df

  member_id  join_date   age     status  monthly_fee
0      M101 2026-01-15  28.0     Active         5000
1      M102 2026-02-15  30.0     Active         8000
2      M103 2026-03-10  41.0     Active         5000
3      M104        NaT  35.0  Cancelled         8000
4      M105 2026-05-01   NaN     Active         5000