In [49]:
import pandas as pd
import numpy as np

In [50]:
df = pd.read_csv('data.csv')
df

  member_id   join_date     age     status monthly_fee
0      M101   2026/1/15      28     Active       5,000
1      M102  15/02/2026  thirty    active         8000
2      M103   2026/3/10      41     ACTIVE        5000
3      M104     invalid      35  cancelled       8,000
4      M105    2026/5/1      -2     Active        5000
5      M105    2026/5/1      -2     Active        5000

In [51]:
df.info

<bound method DataFrame.info of   member_id   join_date     age     status monthly_fee
0      M101   2026/1/15      28     Active       5,000
1      M102  15/02/2026  thirty    active         8000
2      M103   2026/3/10      41     ACTIVE        5000
3      M104     invalid      35  cancelled       8,000
4      M105    2026/5/1      -2     Active        5000
5      M105    2026/5/1      -2     Active        5000>

In [52]:
df.drop_duplicates(inplace=True)
df

  member_id   join_date     age     status monthly_fee
0      M101   2026/1/15      28     Active       5,000
1      M102  15/02/2026  thirty    active         8000
2      M103   2026/3/10      41     ACTIVE        5000
3      M104     invalid      35  cancelled       8,000
4      M105    2026/5/1      -2     Active        5000

In [53]:
df["join_date"] = df["join_date"].apply(lambda x:None if x=="invalid" else pd.to_datetime(x, format="mixed"))
df

  member_id  join_date     age     status monthly_fee
0      M101 2026-01-15      28     Active       5,000
1      M102 2026-02-15  thirty    active         8000
2      M103 2026-03-10      41     ACTIVE        5000
3      M104        NaT      35  cancelled       8,000
4      M105 2026-05-01      -2     Active        5000

In [54]:
df["status"] = df["status"].str.strip().str.capitalize()
df

  member_id  join_date     age     status monthly_fee
0      M101 2026-01-15      28     Active       5,000
1      M102 2026-02-15  thirty     Active        8000
2      M103 2026-03-10      41     Active        5000
3      M104        NaT      35  Cancelled       8,000
4      M105 2026-05-01      -2     Active        5000

In [55]:
df["age"] = df["age"].replace({"thirty":30, "-2":None}).pipe(pd.to_numeric, errors="coerce")
df

  member_id  join_date   age     status monthly_fee
0      M101 2026-01-15  28.0     Active       5,000
1      M102 2026-02-15  30.0     Active        8000
2      M103 2026-03-10  41.0     Active        5000
3      M104        NaT  35.0  Cancelled       8,000
4      M105 2026-05-01   NaN     Active        5000

In [56]:
df["monthly_fee"] = df["monthly_fee"].str.replace(",","").pipe(pd.to_numeric, errors="coerce")
df

  member_id  join_date   age     status  monthly_fee
0      M101 2026-01-15  28.0     Active         5000
1      M102 2026-02-15  30.0     Active         8000
2      M103 2026-03-10  41.0     Active         5000
3      M104        NaT  35.0  Cancelled         8000
4      M105 2026-05-01   NaN     Active         5000

In [57]:
df2 = pd.read_csv("data2.csv")
df2

  member_id  visit_date plan_type  monthly_fee
0      M101  2026-09-02     Basic         5000
1      M102  2026-09-08   Premium         8000
2      M103  2026-08-20     Basic         5000
3      M104  2026-09-05   Premium         8000
4      M105  2026-07-15     Basic         5000

In [58]:
all_df = pd.merge(df,df2.drop(columns=["monthly_fee"]), on="member_id", how="inner")
all_df

  member_id  join_date   age     status  monthly_fee  visit_date plan_type
0      M101 2026-01-15  28.0     Active         5000  2026-09-02     Basic
1      M102 2026-02-15  30.0     Active         8000  2026-09-08   Premium
2      M103 2026-03-10  41.0     Active         5000  2026-08-20     Basic
3      M104        NaT  35.0  Cancelled         8000  2026-09-05   Premium
4      M105 2026-05-01   NaN     Active         5000  2026-07-15     Basic

In [59]:
all_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 7 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   member_id    5 non-null      object
 1   join_date    4 non-null      datetime64[ns]
 2   age          4 non-null      float64
 3   status       5 non-null      object
 4   monthly_fee  5 non-null      int64
 5   visit_date   5 non-null      object
 6   plan_type    5 non-null      object
dtypes: datetime64[ns](1), float64(1), int64(1), object(4)
memory usage: 412.0+ bytes

In [60]:
all_df["visit_date"] = pd.to_datetime(all_df["visit_date"], format="mixed")
all_df

  member_id  join_date   age     status  monthly_fee visit_date plan_type
0      M101 2026-01-15  28.0     Active         5000 2026-09-02     Basic
1      M102 2026-02-15  30.0     Active         8000 2026-09-08   Premium
2      M103 2026-03-10  41.0     Active         5000 2026-08-20     Basic
3      M104        NaT  35.0  Cancelled         8000 2026-09-05   Premium
4      M105 2026-05-01   NaN     Active         5000 2026-07-15     Basic

In [61]:
df = all_df[["member_id","visit_date","join_date","age","plan_type","status","monthly_fee"]]

In [62]:
df

  member_id visit_date  join_date   age plan_type     status  monthly_fee
0      M101 2026-09-02 2026-01-15  28.0     Basic     Active         5000
1      M102 2026-09-08 2026-02-15  30.0   Premium     Active         8000
2      M103 2026-08-20 2026-03-10  41.0     Basic     Active         5000
3      M104 2026-09-05        NaT  35.0   Premium  Cancelled         8000
4      M105 2026-07-15 2026-05-01   NaN     Basic     Active         5000

In [63]:
df.to_csv("complete_data.csv")