In [28]:
import pandas as pd
import numpy as np

In [29]:
df = pd.read_csv('data.csv')
df

  order_id return_date        reason refund_amount approved
0     O102   2026/9/10   wrong size          4,500      Yes
1     O103  10/09/2026       DAMAGED          8000      yes
2     O107   2026/9/12       damaged         5,000        Y
3     O108     invalid  Changed Mind       unknown       No
4     O109   2026/9/14           NaN          2500        N
5     O109   2026/9/14           NaN          2500        N

In [30]:
df.drop_duplicates(inplace=True)

In [31]:
df["return_date"] = df["return_date"].replace("invalid",None).pipe(pd.to_datetime, format="mixed")
df

  order_id return_date        reason refund_amount approved
0     O102  2026-09-10   wrong size          4,500      Yes
1     O103  2026-10-09       DAMAGED          8000      yes
2     O107  2026-09-12       damaged         5,000        Y
3     O108         NaT  Changed Mind       unknown       No
4     O109  2026-09-14           NaN          2500        N

In [32]:
df["reason"] = df["reason"].str.strip().str.capitalize()
df

  order_id return_date        reason refund_amount approved
0     O102  2026-09-10    Wrong size         4,500      Yes
1     O103  2026-10-09       Damaged          8000      yes
2     O107  2026-09-12       Damaged         5,000        Y
3     O108         NaT  Changed mind       unknown       No
4     O109  2026-09-14           NaN          2500        N

In [33]:
df["refund_amount"] = df["refund_amount"].replace({",": "", "unknown": None}, regex=True).pipe(pd.to_numeric, errors='coerce')
df

  order_id return_date        reason  refund_amount approved
0     O102  2026-09-10    Wrong size         4500.0      Yes
1     O103  2026-10-09       Damaged         8000.0      yes
2     O107  2026-09-12       Damaged         5000.0        Y
3     O108         NaT  Changed mind            NaN       No
4     O109  2026-09-14           NaN         2500.0        N

In [34]:
df["approved"] = np.where(df["approved"].str.lower().str.startswith("y", na=False), "Yes", "No")
df

  order_id return_date        reason  refund_amount approved
0     O102  2026-09-10    Wrong size         4500.0      Yes
1     O103  2026-10-09       Damaged         8000.0      Yes
2     O107  2026-09-12       Damaged         5000.0      Yes
3     O108         NaT  Changed mind            NaN       No
4     O109  2026-09-14           NaN         2500.0       No

In [35]:
df2 = pd.read_csv("data2.csv")
df2

  order_id     category  order_amount  returned
0     O101  Electronics         12000     False
1     O102     Clothing          4500      True
2     O103  Electronics          8000      True
3     O104         Home          6200     False
4     O105     Clothing          3000     False
5     O106  Electronics         15000     False
6     O107         Home          5000      True

In [36]:
all_df = pd.merge(df,df2, on="order_id",how="outer")
all_df

,order_id,return_date,reason,refund_amount,approved,category,order_amount,returned
0,O101,NaT,NaN,NaN,NaN,Electronics,12000.0,False
1,O102,2026-09-10,Wrong size,4500.0,Yes,Clothing,4500.0,True
2,O103,2026-10-09,Damaged,8000.0,Yes,Electronics,8000.0,True
3,O104,NaT,NaN,NaN,NaN,Home,6200.0,False
4,O105,NaT,NaN,NaN,NaN,Clothing,3000.0,False
5,O106,NaT,NaN,NaN,NaN,Electronics,15000.0,False
6,O107,2026-09-12,Damaged,5000.0,Yes,Home,5000.0,True
7,O108,NaT,Changed mind,NaN,No,NaN,NaN,NaN
8,O109,2026-09-14,NaN,2500.0,No,NaN,NaN,NaN