In [81]:
import pandas as pd
import numpy as np

In [82]:
df = pd.read_csv('data.csv')
df

  order_id return_date        reason refund_amount approved
0     O102   2026/9/10   wrong size          4,500      Yes
1     O103  10/09/2026       DAMAGED          8000      yes
2     O107   2026/9/12       damaged         5,000        Y
3     O108     invalid  Changed Mind       unknown       No
4     O109   2026/9/14           NaN          2500        N
5     O109   2026/9/14           NaN          2500        N

In [83]:
df["return_date"] = df["return_date"].replace("invalid",None).pipe(pd.to_datetime, format="mixed")
df

  order_id return_date        reason refund_amount approved
0     O102  2026-09-10   wrong size          4,500      Yes
1     O103  2026-10-09       DAMAGED          8000      yes
2     O107  2026-09-12       damaged         5,000        Y
3     O108         NaT  Changed Mind       unknown       No
4     O109  2026-09-14           NaN          2500        N
5     O109  2026-09-14           NaN          2500        N

In [84]:
df["reason"] = df["reason"].str.strip().str.capitalize()
df

  order_id return_date        reason refund_amount approved
0     O102  2026-09-10    Wrong size         4,500      Yes
1     O103  2026-10-09       Damaged          8000      yes
2     O107  2026-09-12       Damaged         5,000        Y
3     O108         NaT  Changed mind       unknown       No
4     O109  2026-09-14           NaN          2500        N
5     O109  2026-09-14           NaN          2500        N

In [85]:
df["refund_amount"] = df["refund_amount"].replace({",": "", "unknown": None}, regex=True).pipe(pd.to_numeric, errors='coerce')
df

  order_id return_date        reason  refund_amount approved
0     O102  2026-09-10    Wrong size         4500.0      Yes
1     O103  2026-10-09       Damaged         8000.0      yes
2     O107  2026-09-12       Damaged         5000.0        Y
3     O108         NaT  Changed mind            NaN       No
4     O109  2026-09-14           NaN         2500.0        N
5     O109  2026-09-14           NaN         2500.0        N

In [86]:
df["approved"] = np.where(df["approved"].str.lower().str.startswith("y", na=False), "Yes", "No")
df

  order_id return_date        reason  refund_amount approved
0     O102  2026-09-10    Wrong size         4500.0      Yes
1     O103  2026-10-09       Damaged         8000.0      Yes
2     O107  2026-09-12       Damaged         5000.0      Yes
3     O108         NaT  Changed mind            NaN       No
4     O109  2026-09-14           NaN         2500.0       No
5     O109  2026-09-14           NaN         2500.0       No