In [19]:
import pandas as pd
import numpy as np

In [20]:
df = pd.read_csv('data.csv')
df

,customer_id,tenure_months,monthly_charge,support_tickets,contract,churned
0,C101,24,"3,000",0,Annual,No
1,C102,3,6000,5,monthly,Yes
2,C103,18,3000,1,ANNUAL,No
3,C104,6,"4,500",4,Monthly,Yes
4,C105,36,6000,0,Annual,No
5,C106,twelve,4500,2,Monthly,No
6,C107,-2,3000,6,monthly,Yes
7,C108,8,unknown,3,Annual,Yes
8,C109,30,4500,1,annual,No
9,C110,2,6000,7,Monthly,Yes
10,C110,2,6000,7,Monthly,Yes
11,C111,15,3000,-1,Annual,No

In [21]:
df.drop_duplicates(inplace=True)
df

,customer_id,tenure_months,monthly_charge,support_tickets,contract,churned
0,C101,24,"3,000",0,Annual,No
1,C102,3,6000,5,monthly,Yes
2,C103,18,3000,1,ANNUAL,No
3,C104,6,"4,500",4,Monthly,Yes
4,C105,36,6000,0,Annual,No
5,C106,twelve,4500,2,Monthly,No
6,C107,-2,3000,6,monthly,Yes
7,C108,8,unknown,3,Annual,Yes
8,C109,30,4500,1,annual,No
9,C110,2,6000,7,Monthly,Yes
11,C111,15,3000,-1,Annual,No

In [22]:
df["tenure_months"] = df["tenure_months"].replace({"twelve":12,"-":""},regex=True).pipe(pd.to_numeric)
df

,customer_id,tenure_months,monthly_charge,support_tickets,contract,churned
0,C101,24,"3,000",0,Annual,No
1,C102,3,6000,5,monthly,Yes
2,C103,18,3000,1,ANNUAL,No
3,C104,6,"4,500",4,Monthly,Yes
4,C105,36,6000,0,Annual,No
5,C106,12,4500,2,Monthly,No
6,C107,2,3000,6,monthly,Yes
7,C108,8,unknown,3,Annual,Yes
8,C109,30,4500,1,annual,No
9,C110,2,6000,7,Monthly,Yes
11,C111,15,3000,-1,Annual,No

In [23]:
df["monthly_charge"] = df["monthly_charge"].replace({",":"","unknown":None},regex=True).pipe(pd.to_numeric)
df

,customer_id,tenure_months,monthly_charge,support_tickets,contract,churned
0,C101,24,3000.0,0,Annual,No
1,C102,3,6000.0,5,monthly,Yes
2,C103,18,3000.0,1,ANNUAL,No
3,C104,6,4500.0,4,Monthly,Yes
4,C105,36,6000.0,0,Annual,No
5,C106,12,4500.0,2,Monthly,No
6,C107,2,3000.0,6,monthly,Yes
7,C108,8,NaN,3,Annual,Yes
8,C109,30,4500.0,1,annual,No
9,C110,2,6000.0,7,Monthly,Yes
11,C111,15,3000.0,-1,Annual,No

In [24]:
df["contract"] = df["contract"].str.strip().str.capitalize()
df

,customer_id,tenure_months,monthly_charge,support_tickets,contract,churned
0,C101,24,3000.0,0,Annual,No
1,C102,3,6000.0,5,Monthly,Yes
2,C103,18,3000.0,1,Annual,No
3,C104,6,4500.0,4,Monthly,Yes
4,C105,36,6000.0,0,Annual,No
5,C106,12,4500.0,2,Monthly,No
6,C107,2,3000.0,6,Monthly,Yes
7,C108,8,NaN,3,Annual,Yes
8,C109,30,4500.0,1,Annual,No
9,C110,2,6000.0,7,Monthly,Yes
11,C111,15,3000.0,-1,Annual,No

In [25]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 11 entries, 0 to 11
Data columns (total 6 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   customer_id      11 non-null     object
 1   tenure_months    11 non-null     int64
 2   monthly_charge   10 non-null     float64
 3   support_tickets  11 non-null     int64
 4   contract         11 non-null     object
 5   churned          11 non-null     object
dtypes: float64(1), int64(2), object(3)
memory usage: 616.0+ bytes