In [37]:
import pandas as pd

In [38]:
df = pd.read_csv("Data.csv")
df

  customer_id  visit_date  rating   amount member
0        C001    2026/8/1     5.0  "1,200"    Yes
1        C002    2026/8/2     4.0      850    yes
2        C003  03-08-2026     NaN  unknown     No
3        C003  03-08-2026     NaN  unknown     No
4        C004     invalid     6.0      950      N
5        C005    2026/8/5     3.0      700      Y

removes duplicate rows

In [39]:
df.drop_duplicates()

  customer_id  visit_date  rating   amount member
0        C001    2026/8/1     5.0  "1,200"    Yes
1        C002    2026/8/2     4.0      850    yes
2        C003  03-08-2026     NaN  unknown     No
4        C004     invalid     6.0      950      N
5        C005    2026/8/5     3.0      700      Y

converts to datetime

In [40]:
df["visit_date"] = df["visit_date"].apply(lambda x:"NaT" if x=="invalid" else pd.to_datetime(x, format="mixed"))
df

  customer_id           visit_date  rating   amount member
0        C001  2026-08-01 00:00:00     5.0  "1,200"    Yes
1        C002  2026-08-02 00:00:00     4.0      850    yes
2        C003  2026-03-08 00:00:00     NaN  unknown     No
3        C003  2026-03-08 00:00:00     NaN  unknown     No
4        C004                  NaT     6.0      950      N
5        C005  2026-08-05 00:00:00     3.0      700      Y