In [40]:
import pandas as pd
import numpy as np

In [41]:
df = pd.read_csv("Data.csv")
df

  customer_id  visit_date  rating   amount member
0        C001    2026/8/1     5.0  "1,200"    Yes
1        C002    2026/8/2     4.0      850    yes
2        C003  03-08-2026     NaN  unknown     No
3        C003  03-08-2026     NaN  unknown     No
4        C004     invalid     6.0      950      N
5        C005    2026/8/5     3.0      700      Y

removes duplicate rows

In [42]:
df.drop_duplicates()

  customer_id  visit_date  rating   amount member
0        C001    2026/8/1     5.0  "1,200"    Yes
1        C002    2026/8/2     4.0      850    yes
2        C003  03-08-2026     NaN  unknown     No
4        C004     invalid     6.0      950      N
5        C005    2026/8/5     3.0      700      Y

converts visit_date to datetime

In [43]:
df["visit_date"] = df["visit_date"].apply(lambda x:"NaT" if x=="invalid" else pd.to_datetime(x, format="mixed"))
df

  customer_id           visit_date  rating   amount member
0        C001  2026-08-01 00:00:00     5.0  "1,200"    Yes
1        C002  2026-08-02 00:00:00     4.0      850    yes
2        C003  2026-03-08 00:00:00     NaN  unknown     No
3        C003  2026-03-08 00:00:00     NaN  unknown     No
4        C004                  NaT     6.0      950      N
5        C005  2026-08-05 00:00:00     3.0      700      Y

converts visit_date to datetime, using NaT for invalid dates

In [44]:
df["rating"] = df["rating"].fillna(df["rating"].mean())
df

  customer_id           visit_date  rating   amount member
0        C001  2026-08-01 00:00:00     5.0  "1,200"    Yes
1        C002  2026-08-02 00:00:00     4.0      850    yes
2        C003  2026-03-08 00:00:00     4.5  unknown     No
3        C003  2026-03-08 00:00:00     4.5  unknown     No
4        C004                  NaT     6.0      950      N
5        C005  2026-08-05 00:00:00     3.0      700      Y

converts amount to numeric

In [45]:
df["amount"] = (df["amount"].astype(str).str.replace(",", "").str.replace('"', ""))
df["amount"] = pd.to_numeric(df["amount"], errors="coerce")
df["amount"] = df["amount"].astype("Int64")
df

  customer_id           visit_date  rating  amount member
0        C001  2026-08-01 00:00:00     5.0    1200    Yes
1        C002  2026-08-02 00:00:00     4.0     850    yes
2        C003  2026-03-08 00:00:00     4.5    <NA>     No
3        C003  2026-03-08 00:00:00     4.5    <NA>     No
4        C004                  NaT     6.0     950      N
5        C005  2026-08-05 00:00:00     3.0     700      Y

standardizes member to Yes or No

In [ ]:
df["member"] = np.where(df["member"].str.lower().str.startswith("y", na=False), "Yes", "No")
df

  customer_id           visit_date  rating  amount member
0        C001  2026-08-01 00:00:00     5.0    1200    Yes
1        C002  2026-08-02 00:00:00     4.0     850    Yes
2        C003  2026-03-08 00:00:00     4.5    <NA>     No
3        C003  2026-03-08 00:00:00     4.5    <NA>     No
4        C004                  NaT     6.0     950     No
5        C005  2026-08-05 00:00:00     3.0     700    Yes