In [31]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [32]:
data = pd.read_csv('../Datasets/verbo_data.csv')
data

,booking_id,guest_name,email,listing_id,listing_city,checkin_date,checkout_date,nights,price_per_night,total_price,payment_status,review_score,is_cancelled
0,BKG-013035,NaN,nhoffman@scott.com,1083,Los Angeles,2023-05-24,2023-12-12,-1,245.61,-245.61,pending,6.0,False
1,BKG-003115,CAROLYN SHAH,achan@olson-nelson.com,1079,los angeles,2024-08-19,2024-11-08,81,51.96,4208.76,NaN,6.0,Yes
2,BKG-008732,Jermaine Huang,thomasadam@yahoo.com,1036,San Fran,2024-03-20,2025-03-03,348,383.63,133503.24,paid,1.0,FALSE
3,BKG-007591,amy rios,reginald31@robertson-smith.com,1025,LA,2024-02-29,2025-03-16,381,268.36,102245.16,pending,6.0,n
4,BKG-000221,NaN,NaN,1089,LA,2025-01-26,2025-02-22,27,134.71,3637.17,PENDING,NaN,TRUE
...,...,...,...,...,...,...,...,...,...,...,...,...,...
21995,BKG-011964,Victoria Bennett,thomasjames@franklin.org,1058,New York,2024-05-04,2025-05-11,372,326.11,121312.92,paid,NaN,False
21996,BKG-015277,NaN,pcompton@gmail.com,1020,SF,2024-04-04,2025-03-26,356,204.59,72834.04000000001,Paid,NaN,False
21997,BKG-005390,STEPHANIE BRIDGES,veronicabyrd@hotmail.com,1027,SF,2025-03-06,2025-04-25,50,176.06,8803.0,NaN,NaN,No
21998,BKG-000860,christian ford,nicoleaguirre@thomas.net,1001,Los Angeles,2024-05-27,2025-03-06,283,282.57,79967.31,Unpaid,NaN,n
21999,BKG-015795,KELLY FORD,heather20@doyle.com,1005,nyc,2024-01-08,2024-12-20,347,312.47,108427.09000000001,NaN,NaN,False

In [33]:
data.isnull().sum()

booking_id            0
guest_name         4365
email              1111
listing_id            0
listing_city          0
checkin_date          0
checkout_date         0
nights              337
price_per_night     470
total_price           0
payment_status     6369
review_score       8801
is_cancelled          0
dtype: int64

In [34]:
data['guest_name'] = data['guest_name'].fillna('Unknown')
data['guest_name'] = data['guest_name'].str.strip().str.title()
data['guest_name'].unique()

array(['Unknown', 'Carolyn Shah', 'Jermaine Huang', ...,
       'Victoria Bennett', 'Christian Ford', 'Kelly Ford'],
      shape=(14640,), dtype=object)

In [35]:
data

,booking_id,guest_name,email,listing_id,listing_city,checkin_date,checkout_date,nights,price_per_night,total_price,payment_status,review_score,is_cancelled
0,BKG-013035,Unknown,nhoffman@scott.com,1083,Los Angeles,2023-05-24,2023-12-12,-1,245.61,-245.61,pending,6.0,False
1,BKG-003115,Carolyn Shah,achan@olson-nelson.com,1079,los angeles,2024-08-19,2024-11-08,81,51.96,4208.76,NaN,6.0,Yes
2,BKG-008732,Jermaine Huang,thomasadam@yahoo.com,1036,San Fran,2024-03-20,2025-03-03,348,383.63,133503.24,paid,1.0,FALSE
3,BKG-007591,Amy Rios,reginald31@robertson-smith.com,1025,LA,2024-02-29,2025-03-16,381,268.36,102245.16,pending,6.0,n
4,BKG-000221,Unknown,NaN,1089,LA,2025-01-26,2025-02-22,27,134.71,3637.17,PENDING,NaN,TRUE
...,...,...,...,...,...,...,...,...,...,...,...,...,...
21995,BKG-011964,Victoria Bennett,thomasjames@franklin.org,1058,New York,2024-05-04,2025-05-11,372,326.11,121312.92,paid,NaN,False
21996,BKG-015277,Unknown,pcompton@gmail.com,1020,SF,2024-04-04,2025-03-26,356,204.59,72834.04000000001,Paid,NaN,False
21997,BKG-005390,Stephanie Bridges,veronicabyrd@hotmail.com,1027,SF,2025-03-06,2025-04-25,50,176.06,8803.0,NaN,NaN,No
21998,BKG-000860,Christian Ford,nicoleaguirre@thomas.net,1001,Los Angeles,2024-05-27,2025-03-06,283,282.57,79967.31,Unpaid,NaN,n
21999,BKG-015795,Kelly Ford,heather20@doyle.com,1005,nyc,2024-01-08,2024-12-20,347,312.47,108427.09000000001,NaN,NaN,False

In [36]:
data.isnull().sum()

booking_id            0
guest_name            0
email              1111
listing_id            0
listing_city          0
checkin_date          0
checkout_date         0
nights              337
price_per_night     470
total_price           0
payment_status     6369
review_score       8801
is_cancelled          0
dtype: int64

In [37]:
data['email'] = data['email'].fillna('Unknown')
data['email'] = data['email'].str.strip().str.title()
data['email'].unique()

array(['Nhoffman@Scott.Com', 'Achan@Olson-Nelson.Com',
       'Thomasadam@Yahoo.Com', ..., 'Veronicabyrd@Hotmail.Com',
       'Nicoleaguirre@Thomas.Net', 'Heather20@Doyle.Com'],
      shape=(18806,), dtype=object)

In [38]:
data.isnull().sum()

booking_id            0
guest_name            0
email                 0
listing_id            0
listing_city          0
checkin_date          0
checkout_date         0
nights              337
price_per_night     470
total_price           0
payment_status     6369
review_score       8801
is_cancelled          0
dtype: int64

In [39]:
data['payment_status'] =data['payment_status'].fillna('Unknown')
data.isnull().sum()

booking_id            0
guest_name            0
email                 0
listing_id            0
listing_city          0
checkin_date          0
checkout_date         0
nights              337
price_per_night     470
total_price           0
payment_status        0
review_score       8801
is_cancelled          0
dtype: int64

In [40]:
data['review_score'] =data['review_score'].fillna('Unknown')
data.isnull().sum()

booking_id           0
guest_name           0
email                0
listing_id           0
listing_city         0
checkin_date         0
checkout_date        0
nights             337
price_per_night    470
total_price          0
payment_status       0
review_score         0
is_cancelled         0
dtype: int64

In [41]:
from dateutil import parser

In [42]:
def parse_date(date_str):
    try:
        return pd.to_datetime(date_str, format="%Y-%m-%d")
    except:
        try:
            return parser.parse(date_str, dayfirst=True)
        except:
            return pd.NaT

data['checkin_date'] = data['checkin_date'].apply(parse_date)
data['checkout_date'] = data['checkout_date'].apply(parse_date)

In [43]:
data[['checkin_date','checkout_date']]

      checkin_date checkout_date
0       2023-05-24    2023-12-12
1       2024-08-19    2024-11-08
2       2024-03-20    2025-03-03
3       2024-02-29    2025-03-16
4       2025-01-26    2025-02-22
...            ...           ...
21995   2024-05-04    2025-05-11
21996   2024-04-04    2025-03-26
21997   2025-03-06    2025-04-25
21998   2024-05-27    2025-03-06
21999   2024-01-08    2024-12-20

[22000 rows x 2 columns]

In [44]:
data['nights'] = (data['checkout_date'] - data['checkin_date']).dt.days
data

,booking_id,guest_name,email,listing_id,listing_city,checkin_date,checkout_date,nights,price_per_night,total_price,payment_status,review_score,is_cancelled
0,BKG-013035,Unknown,Nhoffman@Scott.Com,1083,Los Angeles,2023-05-24,2023-12-12,202,245.61,-245.61,pending,6.0,False
1,BKG-003115,Carolyn Shah,Achan@Olson-Nelson.Com,1079,los angeles,2024-08-19,2024-11-08,81,51.96,4208.76,Unknown,6.0,Yes
2,BKG-008732,Jermaine Huang,Thomasadam@Yahoo.Com,1036,San Fran,2024-03-20,2025-03-03,348,383.63,133503.24,paid,1.0,FALSE
3,BKG-007591,Amy Rios,Reginald31@Robertson-Smith.Com,1025,LA,2024-02-29,2025-03-16,381,268.36,102245.16,pending,6.0,n
4,BKG-000221,Unknown,Unknown,1089,LA,2025-01-26,2025-02-22,27,134.71,3637.17,PENDING,Unknown,TRUE
...,...,...,...,...,...,...,...,...,...,...,...,...,...
21995,BKG-011964,Victoria Bennett,Thomasjames@Franklin.Org,1058,New York,2024-05-04,2025-05-11,372,326.11,121312.92,paid,Unknown,False
21996,BKG-015277,Unknown,Pcompton@Gmail.Com,1020,SF,2024-04-04,2025-03-26,356,204.59,72834.04000000001,Paid,Unknown,False
21997,BKG-005390,Stephanie Bridges,Veronicabyrd@Hotmail.Com,1027,SF,2025-03-06,2025-04-25,50,176.06,8803.0,Unknown,Unknown,No
21998,BKG-000860,Christian Ford,Nicoleaguirre@Thomas.Net,1001,Los Angeles,2024-05-27,2025-03-06,283,282.57,79967.31,Unpaid,Unknown,n
21999,BKG-015795,Kelly Ford,Heather20@Doyle.Com,1005,nyc,2024-01-08,2024-12-20,347,312.47,108427.09000000001,Unknown,Unknown,False

In [45]:
data.isnull().sum()

booking_id           0
guest_name           0
email                0
listing_id           0
listing_city         0
checkin_date         0
checkout_date        0
nights               0
price_per_night    470
total_price          0
payment_status       0
review_score         0
is_cancelled         0
dtype: int64

In [47]:
data['price_per_night'] = data['price_per_night'].fillna('Unknown')
data

,booking_id,guest_name,email,listing_id,listing_city,checkin_date,checkout_date,nights,price_per_night,total_price,payment_status,review_score,is_cancelled
0,BKG-013035,Unknown,Nhoffman@Scott.Com,1083,Los Angeles,2023-05-24,2023-12-12,202,245.61,-245.61,pending,6.0,False
1,BKG-003115,Carolyn Shah,Achan@Olson-Nelson.Com,1079,los angeles,2024-08-19,2024-11-08,81,51.96,4208.76,Unknown,6.0,Yes
2,BKG-008732,Jermaine Huang,Thomasadam@Yahoo.Com,1036,San Fran,2024-03-20,2025-03-03,348,383.63,133503.24,paid,1.0,FALSE
3,BKG-007591,Amy Rios,Reginald31@Robertson-Smith.Com,1025,LA,2024-02-29,2025-03-16,381,268.36,102245.16,pending,6.0,n
4,BKG-000221,Unknown,Unknown,1089,LA,2025-01-26,2025-02-22,27,134.71,3637.17,PENDING,Unknown,TRUE
...,...,...,...,...,...,...,...,...,...,...,...,...,...
21995,BKG-011964,Victoria Bennett,Thomasjames@Franklin.Org,1058,New York,2024-05-04,2025-05-11,372,326.11,121312.92,paid,Unknown,False
21996,BKG-015277,Unknown,Pcompton@Gmail.Com,1020,SF,2024-04-04,2025-03-26,356,204.59,72834.04000000001,Paid,Unknown,False
21997,BKG-005390,Stephanie Bridges,Veronicabyrd@Hotmail.Com,1027,SF,2025-03-06,2025-04-25,50,176.06,8803.0,Unknown,Unknown,No
21998,BKG-000860,Christian Ford,Nicoleaguirre@Thomas.Net,1001,Los Angeles,2024-05-27,2025-03-06,283,282.57,79967.31,Unpaid,Unknown,n
21999,BKG-015795,Kelly Ford,Heather20@Doyle.Com,1005,nyc,2024-01-08,2024-12-20,347,312.47,108427.09000000001,Unknown,Unknown,False

In [48]:
data.isnull().sum()

booking_id         0
guest_name         0
email              0
listing_id         0
listing_city       0
checkin_date       0
checkout_date      0
nights             0
price_per_night    0
total_price        0
payment_status     0
review_score       0
is_cancelled       0
dtype: int64