In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [3]:
data = pd.read_csv('../Datasets/tip.csv')
data

     total_bill   tip     sex smoker   day    time  size
0         16.99  1.01  Female     No   Sun  Dinner     2
1         10.34  1.66    Male     No   Sun  Dinner     3
2         21.01  3.50    Male     No   Sun  Dinner     3
3         23.68  3.31    Male     No   Sun  Dinner     2
4         24.59  3.61  Female     No   Sun  Dinner     4
..          ...   ...     ...    ...   ...     ...   ...
239       29.03  5.92    Male     No   Sat  Dinner     3
240       27.18  2.00  Female    Yes   Sat  Dinner     2
241       22.67  2.00    Male    Yes   Sat  Dinner     2
242       17.82  1.75    Male     No   Sat  Dinner     2
243       18.78  3.00  Female     No  Thur  Dinner     2

[244 rows x 7 columns]

In [4]:
data.isnull().sum()

total_bill    0
tip           0
sex           0
smoker        0
day           0
time          0
size          0
dtype: int64

In [5]:
data.duplicated().sum()

np.int64(1)

In [6]:
data.head()

   total_bill   tip     sex smoker  day    time  size
0       16.99  1.01  Female     No  Sun  Dinner     2
1       10.34  1.66    Male     No  Sun  Dinner     3
2       21.01  3.50    Male     No  Sun  Dinner     3
3       23.68  3.31    Male     No  Sun  Dinner     2
4       24.59  3.61  Female     No  Sun  Dinner     4

In [7]:
data[['total_bill', 'tip']] = data[['total_bill', 'tip']].round()

In [8]:
data

     total_bill  tip     sex smoker   day    time  size
0          17.0  1.0  Female     No   Sun  Dinner     2
1          10.0  2.0    Male     No   Sun  Dinner     3
2          21.0  4.0    Male     No   Sun  Dinner     3
3          24.0  3.0    Male     No   Sun  Dinner     2
4          25.0  4.0  Female     No   Sun  Dinner     4
..          ...  ...     ...    ...   ...     ...   ...
239        29.0  6.0    Male     No   Sat  Dinner     3
240        27.0  2.0  Female    Yes   Sat  Dinner     2
241        23.0  2.0    Male    Yes   Sat  Dinner     2
242        18.0  2.0    Male     No   Sat  Dinner     2
243        19.0  3.0  Female     No  Thur  Dinner     2

[244 rows x 7 columns]