In [10]:
import yfinance as yf
import pandas as pd
import numpy as np

Apple

In [11]:
ticker = yf.Ticker("AAPL")
Apple = ticker.history(period="5y")
Apple.head()

,Open,High,Low,Close,Volume,Dividends,Stock Splits
Date,,,,,,,
2021-08-16 00:00:00-04:00,144.881597,147.466339,142.862587,147.398056,103296000,0.0,0.0
2021-08-17 00:00:00-04:00,146.530006,147.944291,145.418083,146.490997,92229700,0.0,0.0
2021-08-18 00:00:00-04:00,146.110573,147.007913,142.550460,142.755295,86326000,0.0,0.0
2021-08-19 00:00:00-04:00,141.458077,144.354930,140.941131,143.086945,86960300,0.0,0.0
2021-08-20 00:00:00-04:00,143.808724,144.842615,143.164976,144.540253,60549600,0.0,0.0

Nvidia

In [12]:
ticker = yf.Ticker("NVDA")
Nvidia = ticker.history(period="5y")
Nvidia.head()

,Open,High,Low,Close,Volume,Dividends,Stock Splits
Date,,,,,,,
2021-08-16 00:00:00-04:00,20.065595,20.217071,19.385945,19.881233,210876000,0.0,0.0
2021-08-17 00:00:00-04:00,19.617145,19.701853,19.200587,19.390928,204585000,0.0,0.0
2021-08-18 00:00:00-04:00,19.432782,19.566321,18.934506,18.974369,285913000,0.0,0.0
2021-08-19 00:00:00-04:00,19.426804,20.424355,18.697327,19.729757,766555000,0.0,0.0
2021-08-20 00:00:00-04:00,19.922092,20.793080,19.864294,20.744249,675741000,0.0,0.0

Amazon

In [13]:
ticker = yf.Ticker("AMZN")
Amazon = ticker.history(period="5y")
Amazon.head()

,Open,High,Low,Close,Volume,Dividends,Stock Splits
Date,,,,,,,
2021-08-16 00:00:00-04:00,164.149994,165.000000,160.556503,164.949493,66394000,0.0,0.0
2021-08-17 00:00:00-04:00,163.875000,164.024506,161.283997,162.098007,67758000,0.0,0.0
2021-08-18 00:00:00-04:00,162.099503,162.705002,160.000000,160.061005,56086000,0.0,0.0
2021-08-19 00:00:00-04:00,159.701004,161.649994,159.123001,159.387497,75658000,0.0,0.0
2021-08-20 00:00:00-04:00,160.193497,160.390503,158.787994,159.997498,67168000,0.0,0.0

Tesla

In [14]:
ticker = yf.Ticker("TSLA")
Tesla = ticker.history(period="5y")
Tesla.head()

,Open,High,Low,Close,Volume,Dividends,Stock Splits
Date,,,,,,,
2021-08-16 00:00:00-04:00,235.023331,236.500000,225.466660,228.723328,68032200,0.0,0.0
2021-08-17 00:00:00-04:00,224.220001,224.860001,216.279999,221.903336,71163900,0.0,0.0
2021-08-18 00:00:00-04:00,223.250000,231.923340,223.116669,229.663330,61048200,0.0,0.0
2021-08-19 00:00:00-04:00,226.070007,228.850006,222.529999,224.490005,42940500,0.0,0.0
2021-08-20 00:00:00-04:00,227.616669,230.710007,224.566666,226.753326,44525700,0.0,0.0

JPMorgan Chase

In [15]:
ticker = yf.Ticker("JPM")
JPMorgan = ticker.history(period="5y")
JPMorgan.head()

,Open,High,Low,Close,Volume,Dividends,Stock Splits
Date,,,,,,,
2021-08-16 00:00:00-04:00,140.249647,140.329060,138.343646,140.240814,8755800,0.0,0.0
2021-08-17 00:00:00-04:00,139.040774,140.179073,137.011237,138.546616,9347200,0.0,0.0
2021-08-18 00:00:00-04:00,137.928928,139.429016,137.072992,137.284775,8065500,0.0,0.0
2021-08-19 00:00:00-04:00,135.149359,137.267129,135.016990,136.137650,9517700,0.0,0.0
2021-08-20 00:00:00-04:00,136.199439,136.684751,135.149373,136.525925,6974100,0.0,0.0