import libraries

In [1]:
import yfinance as yf
import pandas as pd
import numpy as np

download data

In [2]:
ticker = ["AAPL", "NVDA", "AMZN", "TSLA", "JPM"]

all_ticker_data = []

for ticker_symbol in ticker:

    ticker_data = yf.download(
        ticker_symbol,
        period="5y",
        auto_adjust=False
    )

    ticker_data.columns = ticker_data.columns.get_level_values(0)

    ticker_data = ticker_data.reset_index()

    ticker_data["Ticker"] = ticker_symbol

    all_ticker_data.append(ticker_data)

df = pd.concat(all_ticker_data, ignore_index=True)

df

[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed

Price,Date,Adj Close,Close,High,Low,Open,Volume,Ticker
0,2021-08-24,145.935013,149.619995,150.860001,149.149994,149.449997,48606400,AAPL
1,2021-08-25,144.706070,148.360001,150.320007,147.800003,149.809998,58991300,AAPL
2,2021-08-26,143.906265,147.539993,149.119995,147.509995,148.350006,48597200,AAPL
3,2021-08-27,144.940140,148.600006,148.750000,146.830002,147.479996,55802400,AAPL
4,2021-08-30,149.348831,153.119995,153.490005,148.610001,149.000000,90956700,AAPL
...,...,...,...,...,...,...,...,...
6270,2026-08-18,363.250000,363.250000,363.570007,359.269989,362.339996,5525100,JPM
6271,2026-08-19,357.260010,357.260010,363.049988,355.649994,363.010010,6696200,JPM
6272,2026-08-20,351.549988,351.549988,357.950012,351.549988,357.600006,6799700,JPM
6273,2026-08-21,351.579987,351.579987,356.859985,350.369995,354.070007,8073400,JPM
6274,2026-08-24,356.130005,356.130005,358.279999,352.815002,353.299988,2494204,JPM

In [3]:
df.head()

Price,Date,Adj Close,Close,High,Low,Open,Volume,Ticker
0,2021-08-24,145.935013,149.619995,150.860001,149.149994,149.449997,48606400,AAPL
1,2021-08-25,144.706070,148.360001,150.320007,147.800003,149.809998,58991300,AAPL
2,2021-08-26,143.906265,147.539993,149.119995,147.509995,148.350006,48597200,AAPL
3,2021-08-27,144.940140,148.600006,148.750000,146.830002,147.479996,55802400,AAPL
4,2021-08-30,149.348831,153.119995,153.490005,148.610001,149.000000,90956700,AAPL

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6275 entries, 0 to 6274
Data columns (total 8 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   Date       6275 non-null   datetime64[ns]
 1   Adj Close  6275 non-null   float64
 2   Close      6275 non-null   float64
 3   High       6275 non-null   float64
 4   Low        6275 non-null   float64
 5   Open       6275 non-null   float64
 6   Volume     6275 non-null   int64
 7   Ticker     6275 non-null   object
dtypes: datetime64[ns](1), float64(5), int64(1), object(1)
memory usage: 392.3+ KB

In [5]:
df.describe()

Price,Date,Adj Close,Close,High,Low,Open,Volume
count,6275,6275.000000,6275.000000,6275.000000,6275.000000,6275.000000,6.275000e+03
mean,2024-02-21 14:26:17.689243136,188.676077,190.888451,193.645890,188.011818,190.863659,1.189768e+08
min,2021-08-24 00:00:00,11.199244,11.227000,11.735000,10.813000,10.971000,2.494204e+06
25%,2022-11-18 00:00:00,132.669594,138.050003,139.739998,136.034996,138.125000,3.503095e+07
50%,2024-02-22 00:00:00,181.190002,182.479996,184.800003,179.970001,182.429993,6.162360e+07
75%,2025-05-23 00:00:00,239.239159,241.714996,245.356667,238.025002,242.055000,1.224246e+08
max,2026-08-24 00:00:00,489.880005,489.880005,498.829987,485.329987,489.880005,1.543911e+09
std,NaN,91.720683,91.288656,92.915270,89.665177,91.336689,1.563857e+08

In [6]:
df.shape

(6275, 8)

In [7]:
df.columns

Index(['Date', 'Adj Close', 'Close', 'High', 'Low', 'Open', 'Volume',
       'Ticker'],
      dtype='object', name='Price')

Question 1 — Overall performance

In [8]:
df1 = df[["Date", "Ticker", "Adj Close"]]
df1.columns = ['date', 'ticker', 'price']
df1

           date ticker       price
0    2021-08-24   AAPL  145.935013
1    2021-08-25   AAPL  144.706070
2    2021-08-26   AAPL  143.906265
3    2021-08-27   AAPL  144.940140
4    2021-08-30   AAPL  149.348831
...         ...    ...         ...
6270 2026-08-18    JPM  363.250000
6271 2026-08-19    JPM  357.260010
6272 2026-08-20    JPM  351.549988
6273 2026-08-21    JPM  351.579987
6274 2026-08-24    JPM  356.130005

[6275 rows x 3 columns]

In [9]:
df1 = df1.pivot_table(index=['date'], columns='ticker', values=['price'])
df1.columns = [col[1] for col in df1.columns.values]
df1

                  AAPL        AMZN         JPM        NVDA        TSLA
date
2021-08-24  145.935013  165.289001  139.129028   21.717878  236.163330
2021-08-25  144.706070  164.959000  141.996841   22.136431  237.066666
2021-08-26  143.906265  165.800003  142.729248   21.991932  233.720001
2021-08-27  144.940140  167.481506  143.876373   22.557972  237.306671
2021-08-30  149.348831  171.078506  141.573288   22.609798  243.636673
...                ...         ...         ...         ...         ...
2026-08-18  310.029999  259.450012  363.250000  219.740005  336.869995
2026-08-19  316.829987  265.839996  357.260010  217.559998  351.119995
2026-08-20  311.299988  260.109985  351.549988  216.850006  345.130005
2026-08-21  309.350006  258.630005  351.579987  214.720001  362.859985
2026-08-24  311.040009  262.109985  356.130005  208.714996  349.725006

[1255 rows x 5 columns]

In [10]:
overall_performance = (df1.iloc[-1] - df1.iloc[0]) / df1.iloc[0]
overall_performance * 100

AAPL    113.135972
AMZN     58.576786
JPM     155.971029
NVDA    861.028481
TSLA     48.086075
dtype: float64

Question 2 — Daily returnsDaily returns

In [11]:
daily_return = df1.pct_change().dropna()
daily_return

                AAPL      AMZN       JPM      NVDA      TSLA
date
2021-08-25 -0.008421 -0.001997  0.020613  0.019272  0.003825
2021-08-26 -0.005527  0.005098  0.005158 -0.006528 -0.014117
2021-08-27  0.007184  0.010142  0.008037  0.025739  0.015346
2021-08-30  0.030417  0.021477 -0.016007  0.002297  0.026674
2021-08-31 -0.008425  0.014385 -0.003054 -0.013181  0.006581
...              ...       ...       ...       ...       ...
2026-08-18  0.014529 -0.007118  0.006344 -0.023421 -0.007162
2026-08-19  0.021933  0.024629 -0.016490 -0.009921  0.042301
2026-08-20 -0.017454 -0.021554 -0.015983 -0.003263 -0.017060
2026-08-21 -0.006264 -0.005690  0.000085 -0.009822  0.051372
2026-08-24  0.005463  0.013455  0.012942 -0.027967 -0.036198

[1254 rows x 5 columns]

Question 3 — Volatility

In [ ]:
volatility = (
    daily_return.std().round(2)
)

In [13]:
volatility

AAPL    0.02
AMZN    0.02
JPM     0.02
NVDA    0.03
TSLA    0.04
dtype: float64

Question 4 — Moving averages

In [16]:
df["year"] = df["Date"].dt.year
df["month"] = df["Date"].dt.month
df["weekday"] = df["Date"].dt.day_name()

df

Price,Date,Adj Close,Close,High,Low,Open,Volume,Ticker,year,month,weekday
0,2021-08-24,145.935013,149.619995,150.860001,149.149994,149.449997,48606400,AAPL,2021,8,Tuesday
1,2021-08-25,144.706070,148.360001,150.320007,147.800003,149.809998,58991300,AAPL,2021,8,Wednesday
2,2021-08-26,143.906265,147.539993,149.119995,147.509995,148.350006,48597200,AAPL,2021,8,Thursday
3,2021-08-27,144.940140,148.600006,148.750000,146.830002,147.479996,55802400,AAPL,2021,8,Friday
4,2021-08-30,149.348831,153.119995,153.490005,148.610001,149.000000,90956700,AAPL,2021,8,Monday
...,...,...,...,...,...,...,...,...,...,...,...
6270,2026-08-18,363.250000,363.250000,363.570007,359.269989,362.339996,5525100,JPM,2026,8,Tuesday
6271,2026-08-19,357.260010,357.260010,363.049988,355.649994,363.010010,6696200,JPM,2026,8,Wednesday
6272,2026-08-20,351.549988,351.549988,357.950012,351.549988,357.600006,6799700,JPM,2026,8,Thursday
6273,2026-08-21,351.579987,351.579987,356.859985,350.369995,354.070007,8073400,JPM,2026,8,Friday
6274,2026-08-24,356.130005,356.130005,358.279999,352.815002,353.299988,2494204,JPM,2026,8,Monday

In [18]:
df["daytype"] = df["weekday"].apply(
    lambda x:"weekend"
    if x in ["saturday","sunday"]
    else "weekday"
)
df

Price,Date,Adj Close,Close,High,Low,Open,Volume,Ticker,year,month,weekday,daytype
0,2021-08-24,145.935013,149.619995,150.860001,149.149994,149.449997,48606400,AAPL,2021,8,Tuesday,weekday
1,2021-08-25,144.706070,148.360001,150.320007,147.800003,149.809998,58991300,AAPL,2021,8,Wednesday,weekday
2,2021-08-26,143.906265,147.539993,149.119995,147.509995,148.350006,48597200,AAPL,2021,8,Thursday,weekday
3,2021-08-27,144.940140,148.600006,148.750000,146.830002,147.479996,55802400,AAPL,2021,8,Friday,weekday
4,2021-08-30,149.348831,153.119995,153.490005,148.610001,149.000000,90956700,AAPL,2021,8,Monday,weekday
...,...,...,...,...,...,...,...,...,...,...,...,...
6270,2026-08-18,363.250000,363.250000,363.570007,359.269989,362.339996,5525100,JPM,2026,8,Tuesday,weekday
6271,2026-08-19,357.260010,357.260010,363.049988,355.649994,363.010010,6696200,JPM,2026,8,Wednesday,weekday
6272,2026-08-20,351.549988,351.549988,357.950012,351.549988,357.600006,6799700,JPM,2026,8,Thursday,weekday
6273,2026-08-21,351.579987,351.579987,356.859985,350.369995,354.070007,8073400,JPM,2026,8,Friday,weekday
6274,2026-08-24,356.130005,356.130005,358.279999,352.815002,353.299988,2494204,JPM,2026,8,Monday,weekday