import libraries

In [30]:
import yfinance as yf
import pandas as pd
import numpy as np

download data

In [31]:
ticker = ["AAPL", "NVDA", "AMZN", "TSLA", "JPM"]

all_ticker_data = []

for ticker_symbol in ticker:

    ticker_data = yf.download(
        ticker_symbol,
        period="5y",
        auto_adjust=False
    )

    ticker_data.columns = ticker_data.columns.get_level_values(0)

    ticker_data = ticker_data.reset_index()

    ticker_data["Ticker"] = ticker_symbol

    all_ticker_data.append(ticker_data)

df = pd.concat(all_ticker_data, ignore_index=True)

df

[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed

Price,Date,Adj Close,Close,High,Low,Open,Volume,Ticker
0,2021-08-25,144.706085,148.360001,150.320007,147.800003,149.809998,58991300,AAPL
1,2021-08-26,143.906235,147.539993,149.119995,147.509995,148.350006,48597200,AAPL
2,2021-08-27,144.940201,148.600006,148.750000,146.830002,147.479996,55802400,AAPL
3,2021-08-30,149.348831,153.119995,153.490005,148.610001,149.000000,90956700,AAPL
4,2021-08-31,148.090591,151.830002,152.800003,151.289993,152.660004,86453100,AAPL
...,...,...,...,...,...,...,...,...
6265,2026-08-18,363.250000,363.250000,363.570007,359.269989,362.339996,5525100,JPM
6266,2026-08-19,357.260010,357.260010,363.049988,355.649994,363.010010,6696200,JPM
6267,2026-08-20,351.549988,351.549988,357.950012,351.549988,357.600006,6799700,JPM
6268,2026-08-21,351.579987,351.579987,356.859985,350.369995,354.070007,8073400,JPM
6269,2026-08-24,356.390015,356.390015,358.279999,352.815002,353.299988,4236267,JPM

In [32]:
df.head()

Price,Date,Adj Close,Close,High,Low,Open,Volume,Ticker
0,2021-08-25,144.706085,148.360001,150.320007,147.800003,149.809998,58991300,AAPL
1,2021-08-26,143.906235,147.539993,149.119995,147.509995,148.350006,48597200,AAPL
2,2021-08-27,144.940201,148.600006,148.750000,146.830002,147.479996,55802400,AAPL
3,2021-08-30,149.348831,153.119995,153.490005,148.610001,149.000000,90956700,AAPL
4,2021-08-31,148.090591,151.830002,152.800003,151.289993,152.660004,86453100,AAPL

In [33]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6270 entries, 0 to 6269
Data columns (total 8 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   Date       6270 non-null   datetime64[ns]
 1   Adj Close  6270 non-null   float64
 2   Close      6270 non-null   float64
 3   High       6270 non-null   float64
 4   Low        6270 non-null   float64
 5   Open       6270 non-null   float64
 6   Volume     6270 non-null   int64
 7   Ticker     6270 non-null   object
dtypes: datetime64[ns](1), float64(5), int64(1), object(1)
memory usage: 392.0+ KB

In [34]:
df.describe()

Price,Date,Adj Close,Close,High,Low,Open,Volume
count,6270,6270.000000,6270.000000,6270.000000,6270.000000,6270.000000,6.270000e+03
mean,2024-02-22 07:53:06.602870528,188.713343,190.923924,193.683000,188.045845,190.899580,1.190132e+08
min,2021-08-25 00:00:00,11.199244,11.227000,11.735000,10.813000,10.971000,3.220500e+06
25%,2022-11-21 00:00:00,132.663074,138.040001,139.734997,136.032497,138.122498,3.505418e+07
50%,2024-02-22 12:00:00,181.224434,182.510002,184.815002,180.000000,182.494995,6.164080e+07
75%,2025-05-23 00:00:00,239.287079,241.812496,245.390827,238.067501,242.122501,1.225155e+08
max,2026-08-24 00:00:00,489.880005,489.880005,498.829987,485.329987,489.880005,1.543911e+09
std,NaN,91.726551,91.294958,92.921998,89.671603,91.343154,1.564141e+08

In [35]:
df.shape

(6270, 8)

In [36]:
df.columns

Index(['Date', 'Adj Close', 'Close', 'High', 'Low', 'Open', 'Volume',
       'Ticker'],
      dtype='object', name='Price')

Question 1 — Overall performance

In [37]:
df1 = df[["Date", "Ticker", "Adj Close"]]
df1.columns = ['date', 'ticker', 'price']
df1

           date ticker       price
0    2021-08-25   AAPL  144.706085
1    2021-08-26   AAPL  143.906235
2    2021-08-27   AAPL  144.940201
3    2021-08-30   AAPL  149.348831
4    2021-08-31   AAPL  148.090591
...         ...    ...         ...
6265 2026-08-18    JPM  363.250000
6266 2026-08-19    JPM  357.260010
6267 2026-08-20    JPM  351.549988
6268 2026-08-21    JPM  351.579987
6269 2026-08-24    JPM  356.390015

[6270 rows x 3 columns]

In [38]:
df1 = df1.pivot_table(index=['date'], columns='ticker', values=['price'])
df1.columns = [col[1] for col in df1.columns.values]
df1

                  AAPL        AMZN         JPM        NVDA        TSLA
date
2021-08-25  144.706085  164.959000  141.996841   22.136433  237.066666
2021-08-26  143.906235  165.800003  142.729218   21.991932  233.720001
2021-08-27  144.940201  167.481506  143.876373   22.557978  237.306671
2021-08-30  149.348831  171.078506  141.573257   22.609798  243.636673
2021-08-31  148.090591  173.539505  141.140915   22.311777  245.240005
...                ...         ...         ...         ...         ...
2026-08-18  310.029999  259.450012  363.250000  219.740005  336.869995
2026-08-19  316.829987  265.839996  357.260010  217.559998  351.119995
2026-08-20  311.299988  260.109985  351.549988  216.850006  345.130005
2026-08-21  309.350006  258.630005  351.579987  214.720001  362.859985
2026-08-24  310.339996  262.070007  356.390015  208.479996  348.950012

[1254 rows x 5 columns]

In [39]:
overall_performance = (df1.iloc[-1] - df1.iloc[0]) / df1.iloc[0]
overall_performance * 100

AAPL    114.462298
AMZN     58.869785
JPM     150.984466
NVDA    841.795813
TSLA     47.194888
dtype: float64

Question 2 — Daily returnsDaily returns

In [40]:
daily_return = df1.pct_change().dropna()
daily_return

                AAPL      AMZN       JPM      NVDA      TSLA
date
2021-08-26 -0.005527  0.005098  0.005158 -0.006528 -0.014117
2021-08-27  0.007185  0.010142  0.008037  0.025739  0.015346
2021-08-30  0.030417  0.021477 -0.016008  0.002297  0.026674
2021-08-31 -0.008425  0.014385 -0.003054 -0.013181  0.006581
2021-09-01  0.004479  0.002365 -0.001438  0.002502 -0.002216
...              ...       ...       ...       ...       ...
2026-08-18  0.014529 -0.007118  0.006344 -0.023421 -0.007162
2026-08-19  0.021933  0.024629 -0.016490 -0.009921  0.042301
2026-08-20 -0.017454 -0.021554 -0.015983 -0.003263 -0.017060
2026-08-21 -0.006264 -0.005690  0.000085 -0.009822  0.051372
2026-08-24  0.003200  0.013301  0.013681 -0.029061 -0.038334

[1253 rows x 5 columns]

Question 3 — Volatility

In [41]:
volatility = (
    daily_return.std().round(2)
)

In [42]:
volatility

AAPL    0.02
AMZN    0.02
JPM     0.02
NVDA    0.03
TSLA    0.04
dtype: float64

Question 4 — Moving averages

In [43]:
df["MA7"] = (
    df
    .groupby("Ticker")["Adj Close"]
    .transform(
        lambda x:
        x.rolling(7).mean()
    )
)
df

Price,Date,Adj Close,Close,High,Low,Open,Volume,Ticker,MA7
0,2021-08-25,144.706085,148.360001,150.320007,147.800003,149.809998,58991300,AAPL,NaN
1,2021-08-26,143.906235,147.539993,149.119995,147.509995,148.350006,48597200,AAPL,NaN
2,2021-08-27,144.940201,148.600006,148.750000,146.830002,147.479996,55802400,AAPL,NaN
3,2021-08-30,149.348831,153.119995,153.490005,148.610001,149.000000,90956700,AAPL,NaN
4,2021-08-31,148.090591,151.830002,152.800003,151.289993,152.660004,86453100,AAPL,NaN
...,...,...,...,...,...,...,...,...,...
6265,2026-08-18,363.250000,363.250000,363.570007,359.269989,362.339996,5525100,JPM,362.452855
6266,2026-08-19,357.260010,357.260010,363.049988,355.649994,363.010010,6696200,JPM,362.091426
6267,2026-08-20,351.549988,351.549988,357.950012,351.549988,357.600006,6799700,JPM,360.592852
6268,2026-08-21,351.579987,351.579987,356.859985,350.369995,354.070007,8073400,JPM,358.649994
6269,2026-08-24,356.390015,356.390015,358.279999,352.815002,353.299988,4236267,JPM,357.689998

In [44]:
df["MA30"] = (
    df
    .groupby("Ticker")["Adj Close"]
    .transform(
        lambda x:
        x.rolling(30).mean()
    )
)
df

Price,Date,Adj Close,Close,High,Low,Open,Volume,Ticker,MA7,MA30
0,2021-08-25,144.706085,148.360001,150.320007,147.800003,149.809998,58991300,AAPL,NaN,NaN
1,2021-08-26,143.906235,147.539993,149.119995,147.509995,148.350006,48597200,AAPL,NaN,NaN
2,2021-08-27,144.940201,148.600006,148.750000,146.830002,147.479996,55802400,AAPL,NaN,NaN
3,2021-08-30,149.348831,153.119995,153.490005,148.610001,149.000000,90956700,AAPL,NaN,NaN
4,2021-08-31,148.090591,151.830002,152.800003,151.289993,152.660004,86453100,AAPL,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...
6265,2026-08-18,363.250000,363.250000,363.570007,359.269989,362.339996,5525100,JPM,362.452855,350.926999
6266,2026-08-19,357.260010,357.260010,363.049988,355.649994,363.010010,6696200,JPM,362.091426,351.814999
6267,2026-08-20,351.549988,351.549988,357.950012,351.549988,357.600006,6799700,JPM,360.592852,352.350999
6268,2026-08-21,351.579987,351.579987,356.859985,350.369995,354.070007,8073400,JPM,358.649994,352.854665
6269,2026-08-24,356.390015,356.390015,358.279999,352.815002,353.299988,4236267,JPM,357.689998,353.583332

In [45]:
df["MA90"] = (
    df
    .groupby("Ticker")["Adj Close"]
    .transform(
        lambda x:
        x.rolling(90).mean()
    )
)
df

Price,Date,Adj Close,Close,High,Low,Open,Volume,Ticker,MA7,MA30,MA90
0,2021-08-25,144.706085,148.360001,150.320007,147.800003,149.809998,58991300,AAPL,NaN,NaN,NaN
1,2021-08-26,143.906235,147.539993,149.119995,147.509995,148.350006,48597200,AAPL,NaN,NaN,NaN
2,2021-08-27,144.940201,148.600006,148.750000,146.830002,147.479996,55802400,AAPL,NaN,NaN,NaN
3,2021-08-30,149.348831,153.119995,153.490005,148.610001,149.000000,90956700,AAPL,NaN,NaN,NaN
4,2021-08-31,148.090591,151.830002,152.800003,151.289993,152.660004,86453100,AAPL,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...
6265,2026-08-18,363.250000,363.250000,363.570007,359.269989,362.339996,5525100,JPM,362.452855,350.926999,324.943118
6266,2026-08-19,357.260010,357.260010,363.049988,355.649994,363.010010,6696200,JPM,362.091426,351.814999,325.485115
6267,2026-08-20,351.549988,351.549988,357.950012,351.549988,357.600006,6799700,JPM,360.592852,352.350999,325.921523
6268,2026-08-21,351.579987,351.579987,356.859985,350.369995,354.070007,8073400,JPM,358.649994,352.854665,326.386582
6269,2026-08-24,356.390015,356.390015,358.279999,352.815002,353.299988,4236267,JPM,357.689998,353.583332,326.962494